databases:
  - name: quizzo-db
    plan: free
    databaseName: quizzo
    user: quizzo

services:
  - type: web
    name: quizzo-club
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: quizzo-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
