// Run: node server/seeds/pop_quizzes.js
// Seeds pop culture quiz categories:
//   beliebers (150q), zara_larsson, the_office, friends, game_of_thrones, harry_potter

try { require('dotenv').config(); } catch {}
const { Pool } = require('pg');
const { shuffleQuestionOptions } = require('../lib/questions');

const pool = new Pool({
  connectionString: process.env.DATABASE_URL || 'postgresql://localhost/quizzo',
  ssl: process.env.DATABASE_URL ? { rejectUnauthorized: false } : false,
});

function q(question, options, correct, difficulty = 'medium') {
  return { question, options, correct_index: correct, difficulty };
}

const categories = [
  { id: 'beliebers',        name: 'Beliebers',         emoji: '🎤', description: 'Justin Bieber — karijera, pjesme, život', color: '#7C3AED' },
  { id: 'zara_larsson',     name: 'Zara Larsson',      emoji: '💜', description: 'Zara Larsson — pop zvijezda iz Švedske',  color: '#DB2777' },
  { id: 'the_office',       name: 'The Office',        emoji: '📎', description: 'Dunder Mifflin i ekipa iz Scrantona',     color: '#2563EB' },
  { id: 'friends',          name: 'Friends',           emoji: '☕', description: 'Rachel, Monica, Chandler, Joey, Ross i Phoebe', color: '#D97706' },
  { id: 'game_of_thrones',  name: 'Game of Thrones',   emoji: '🐉', description: 'Westeros, kuće, zmajevi i željezno prijestolje', color: '#DC2626' },
  { id: 'harry_potter',     name: 'Harry Potter',      emoji: '⚡', description: 'Hogwarts, čarolije i magični svijet',     color: '#16A34A' },
];

const questions = {

  // ─── BELIEBERS (150 questions) ─────────────────────────────────────────────
  beliebers: [
    // Early life & discovery
    q('U kojoj je državi Justin Bieber rođen?', ['Kanada','SAD','Australija','Velika Britanija'], 0, 'easy'),
    q('U kojom gradu je Justin Bieber odrastao?', ['London, Ontario','Toronto','Vancouver','Stratford'], 3, 'medium'),
    q('Kada je Justin Bieber rođen?', ['1. ožujka 1994.','14. veljače 1994.','1. ožujka 1995.','14. veljače 1995.'], 0, 'easy'),
    q('Tko je otkrio Justina Biebera na YouTubeu?', ['Scooter Braun','Simon Cowell','Ryan Seacrest','L.A. Reid'], 0, 'easy'),
    q('Koji je Justinov majčin naziv na YouTubeu gdje je objavljao videozapise?', ['kidrauhl','justinbieber','bieberofficial','jbiebs'], 0, 'hard'),
    q('Koliko je godina imao Justin Bieber kada je potpisao ugovor s Island Records?', ['13','14','15','12'], 0, 'medium'),
    q('Koji pjevač/izvođač je preuzeo Justina Biebera pod mentorstvo?', ['Usher','Jay-Z','Kanye West','P. Diddy'], 0, 'easy'),
    q('Koji je bio Justinov prvi singl?', ['One Time','Baby','Somebody to Love','Bigger'], 0, 'medium'),
    q('U kojoj je godini izašao Justinov debitantski EP "My World"?', ['2009','2010','2008','2011'], 0, 'medium'),
    q('Koja pjesma s albuma "My World 2.0" je postala globalni hit s gostovanjem Ludacrisa?', ['Baby','Somebody to Love','Never Let You Go','U Smile'], 0, 'easy'),
    q('Koji Justinov album sadrži hit "Boyfriend"?', ['Believe','My World 2.0','Purpose','Under the Mistletoe'], 0, 'medium'),
    q('Koja je Justinova prva broj 1 pjesma na Billboard Hot 100?', ['What Do You Mean?','Baby','Sorry','Love Yourself'], 0, 'hard'),
    q('Na kojoj se godini vratio s albumom "Purpose"?', ['2015','2016','2014','2017'], 0, 'medium'),
    q('Koji producent je radio na albumu "Purpose"?', ['Skrillex i Diplo','Calvin Harris','Pharrell Williams','Max Martin'], 0, 'medium'),
    q('Koja je pjesma s albuma "Purpose" bila broj 1 na listi Billboard Hot 100?', ['What Do You Mean?','Sorry','Love Yourself','Company'], 0, 'easy'),
    q('Tko je napisao pjesmu "Love Yourself" za Justina Biebera?', ['Ed Sheeran','Taylor Swift','Ariana Grande','Shawn Mendes'], 0, 'medium'),
    q('Koji je album Justin Bieber objavio 2020. godine?', ['Changes','Justice','Purpose','Journals'], 0, 'easy'),
    q('S kime je Justin Bieber otpjevao "Holy" (2020)?', ['Chance the Rapper','Drake','Lil Uzi Vert','Post Malone'], 0, 'medium'),
    q('Koji hit s albuma "Justice" (2021.) uključuje sample Benny Blancoa?', ['Peaches','Ghost','Anyone','Lonely'], 0, 'medium'),
    q('Tko pjeva na hitu "Peaches" uz Justina Biebera?', ['Daniel Caesar i Giveon','The Weeknd i Drake','Khalid i Post Malone','Juice WRLD i Lil Uzi'], 0, 'medium'),
    // Relationships & personal life
    q('S kojom je pjevačicom Justin Bieber bio u dugoj vezi (2010–2018, s prekidima)?', ['Selena Gomez','Taylor Swift','Ariana Grande','Demi Lovato'], 0, 'easy'),
    q('Kako se zove Justinova supruga?', ['Hailey Baldwin','Sofia Richie','Madison Beer','Kendall Jenner'], 0, 'easy'),
    q('U kojoj godini su se Justin i Hailey vjenčali?', ['2018','2019','2020','2017'], 0, 'medium'),
    q('Koji je Hailey Baldwinov poznatiji otac glumac?', ['Stephen Baldwin','Alec Baldwin','Billy Baldwin','Daniel Baldwin'], 0, 'medium'),
    q('S kojom je bolešću Justin Bieber javno obznanio borbu 2019. godine?', ['Lymska bolest','Dijabetes','Astma','Epilepsija'], 0, 'medium'),
    q('Koji sindrom je uzrokovao Justinovu parcijalnu paralizu lica 2022.?', ['Ramsay Hunt sindrom','Bellova pareza','Lymska bolest','Trigeminalna neuralgija'], 0, 'hard'),
    q('U kojoj je godini Justin Bieber uhićen u Miamiju zbog vožnje pod utjecajem?', ['2014','2013','2015','2012'], 0, 'medium'),
    q('Koji je Justinov menadžer od samog početka karijere?', ['Scooter Braun','Troy Carter','Irving Azoff','Guy Oseary'], 0, 'easy'),
    q('Na koji je vjeri Justin Bieber?', ['Kršćanstvo','Islam','Judaizam','Budizam'], 0, 'easy'),
    q('Kojoj crkvenoj zajednici pripada Justin Bieber?', ['Hillsong Church','Catholic Church','Baptist Church','Methodist Church'], 0, 'medium'),
    q('Koji je Justinov omiljeni sportski tim u basketu?', ['Cleveland Cavaliers','Chicago Bulls','LA Lakers','Toronto Raptors'], 0, 'hard'),
    q('Kako se zove Justinova influencerska supruga na Instagramu?', ['Hailey Bieber','Hailey Baldwin','Hailey Bieber Baldwin','h.bieber'], 0, 'easy'),
    q('Koji je tatoo istaknuto na Justinovu licu/vratu?', ['Rose na vratu','Krila na čelu','Ruža na obrazu','Zvijezda na bradi'], 0, 'hard'),
    q('U kojoj je godini Justin Bieber objavio autobiografski film "Never Say Never"?', ['2011','2012','2013','2010'], 0, 'medium'),
    q('Koja je Justinova majka?', ['Pattie Mallette','Diane Bieber','Sarah Bieber','Linda Bieber'], 0, 'medium'),
    // Music & albums
    q('Koji je album Justin Bieber objavio za Božić 2011.?', ['Under the Mistletoe','Believe','My World 2.0','Journals'], 0, 'medium'),
    q('Koliko pjesama ima na albumu "Believe" (2012)?', ['12','10','14','16'], 0, 'hard'),
    q('Koji je bio prvi Justinov singl na albumu "Changes"?', ['Yummy','Intentions','Available','Get Me'], 0, 'easy'),
    q('S kojom je pjevačicom Justin Bieber otpjevao "As Long as You Love Me"?', ['Nije gostovanje — solo je','Nicki Minaj','Ariana Grande','Victoria Justice'], 0, 'hard'),
    q('Koji je Justinov hit iz 2015. koji počinje s "Everybody knows one chance is all you need"?', ['What Do You Mean?','Sorry','Where Are Ü Now','I\'ll Show You'], 0, 'easy'),
    q('S kojim DJ duom (Jack Ü) je Justin surađivao na "Where Are Ü Now"?', ['Skrillex i Diplo','The Chainsmokers','Marshmello i Martin Garrix','Zedd i DJ Snake'], 0, 'medium'),
    q('Koji je album donio Justinu Grammy za Best Dance Recording?', ['Purpose (Where Are Ü Now)','Changes','Justice','Believe'], 0, 'medium'),
    q('Koja je pjesma s "Purpose" bila inspirirana Seleninom putem prema oporavku?', ['Sorry','Love Yourself','Fast Car','No Pressure'], 0, 'hard'),
    q('Koji je Justinov hit 2012. koristio sample "Cry Me a River" (Justin Timberlake)?', ['Nema — nije koristio taj sample','As Long as You Love Me','Beauty and a Beat','Right Here'], 0, 'hard'),
    q('Koji je Justinov hit bio prvi da premaši 10 milijardi streamova na Spotifyju?', ['Baby','Sorry','Love Yourself','What Do You Mean?'], 2, 'hard'),
    q('S kim je Justin Bieber snimio "Despacito Remix" 2017.?', ['Luis Fonsi i Daddy Yankee','J Balvin i Ozuna','Bad Bunny i Maluma','Nicky Jam i Enrique Iglesias'], 0, 'easy'),
    q('Koji je rekord "Baby" postavila na YouTubeu?', ['Bila je najgledaniji video na YT godinama','Prva video sa 1B pregleda','Prva video s 2B pregleda','Video s najviše dislikova'], 0, 'medium'),
    q('Koji je Justinov album iz 2013. — mixtape s brojnim coversima?', ['Journals','Believe Acoustic','My Worlds Acoustic','#mycalvins'], 0, 'easy'),
    q('Tko je producirao velik dio albuma "Believe"?', ['Max Martin i Rodney Jerkins','Timbaland','Kanye West','Pharrell Williams'], 0, 'hard'),
    q('Koji je Justinov hit koji uzorkuje "If I Was Your Boyfriend" iz 2012.?', ['Boyfriend','Nema song tog naslova','Die in Your Arms','All Around the World'], 0, 'easy'),
    q('Koji duet je Justin Bieber snimio s Arianom Grande 2015. za božićni period?', ['Santa Claus Is Coming to Town','Almost Do','Stuck in the Moment','Mistletoe'], 0, 'hard'),
    q('S kojim R&B artistom je Justin snimio "PYD" (Put You Down)?', ['R. Kelly (kontroverzno)','Tyga','Chris Brown','Trey Songz'], 0, 'hard'),
    q('Koja je bila Justinova najboljeprodavanija pjesma na iTunes u 2015.?', ['What Do You Mean?','Sorry','Love Yourself','Company'], 0, 'medium'),
    q('S kim je Justin Bieber nastupao na Coachelli 2025. u sklopu nastupa Tylera the Creatora?', ['Tyler the Creator','Kendrick Lamar','Kanye West','Drake'], 0, 'easy'),
    q('Koja Justin Bieberova pjesma sadrži stih "Is it too late now to say sorry?"?', ['Sorry','Love Yourself','What Do You Mean?','No Pressure'], 0, 'easy'),
    // Tours & performances
    q('Kako se zvala Justinova turneja iz 2013.?', ['Believe Tour','My World Tour','Purpose World Tour','Changes Tour'], 0, 'medium'),
    q('Koji je Justinov tour iz 2016. bio jedan od najuspješnijih ikad?', ['Purpose World Tour','Believe Tour','My World Tour','Justice World Tour'], 0, 'easy'),
    q('Koliko je gradova obuhvatila "Purpose World Tour"?', ['Više od 100','Oko 60','Oko 40','Oko 80'], 0, 'hard'),
    q('Na kojemu festivalskom nastupu je Justin Bieber nastupio 2012. na MTV VMAs?', ['MTV VMAs 2012. s "As Long as You Love Me"','Coachella 2012','Glastonbury 2012','Lollapalooza 2012'], 0, 'medium'),
    q('Koji je Justin Bieber tour dokumentiran u Netflix seriji 2020.?', ['Seasons','Never Say Never','Justin Bieber: Our World','Believe'], 2, 'medium'),
    // Collaborations
    q('S kojom je pjevačicom Justin Bieber surađivao na "Beauty and a Beat"?', ['Nicki Minaj','Rihanna','Beyoncé','Cardi B'], 0, 'easy'),
    q('Tko gostuje na Justinovu pjesmu "All Around the World"?', ['Ludacris','Lil Wayne','T.I.','Wiz Khalifa'], 0, 'hard'),
    q('Na čijoj pjesmi je Justin Bieber gostovao ("10,000 Hours") 2019.?', ['Dan + Shay','Sam Hunt','Luke Bryan','Kane Brown'], 0, 'medium'),
    q('S kime je Justin Bieber snimio "Let Me Love You" 2016.?', ['DJ Snake','Martin Garrix','Marshmello','Kygo'], 0, 'easy'),
    q('Tko je gostovao na Justinovu hitu "Cold Water" (2016.) uz Major Lazer?', ['MØ','Dua Lipa','Ellie Goulding','Charli XCX'], 0, 'medium'),
    q('Na kojoj Usherovoj pjesmi je mladi Justin Bieber gostovao?', ['First Dance','OMG','DJ Got Us Fallin\' in Love','There Goes My Baby'], 0, 'easy'),
    q('Koji američki pjevač je gostovao na "Intentions" uz Justina Biebera (2020.)?', ['Quavo','Offset','Lil Baby','DaBaby'], 0, 'medium'),
    q('S kojim je izvođačem Justin Bieber snimio "Ghost / Monster" (2021.)?', ['Shawn Mendes','Niall Horan','Ed Sheeran','Harry Styles'], 0, 'easy'),
    q('Na čijoj pjesmi "I Don\'t Care" je Justin Bieber gostovao 2019.?', ['Ed Sheeran','Sam Smith','Lewis Capaldi','James Arthur'], 0, 'easy'),
    q('Koji hit Justina i The Kida Laroia je izašao 2020.?', ['Stay','Lonely','Holy','Anyone'], 0, 'easy'),
    // Awards & records
    q('Koliko je Justin Bieber Grammy nagrada ukupno osvojio?', ['2','1','3','0'], 0, 'hard'),
    q('Za koji je hit Justin Bieber dobio Grammy za Best Dance Recording?', ['Where Are Ü Now','Sorry','Love Yourself','What Do You Mean?'], 0, 'medium'),
    q('Koliko je Justin Bieber AMAs (American Music Awards) osvojio u karijeri?', ['Više od 25','Oko 15','Oko 10','Oko 5'], 0, 'hard'),
    q('Koji rekord Guinness Book-a drži Justin Bieber?', ['Više rekorda — npr. najpraćeniji muškarac na Twitteru u neko doba','Najmlađi album s 1B streamova','Najbrže prodan singl ikad','Jedini artist s 5 broj-1 singla mlađi od 18'], 0, 'medium'),
    q('Koji je Justin Bieber osvajao Kid\'s Choice Awards za omiljenog pjevača?', ['Više puta zaredom','Jednom','Nikada nije osvajao','Tri puta'], 0, 'easy'),
    q('Justin Bieber je bio nominiran za Oscar za Best Original Song. Za koji film?', ['Nije nominiran za Oscar','Trolls','Sing','La La Land'], 0, 'hard'),
    q('Na kojoj listi je Justin Bieber bio uvršten medu "100 najutjecajnijih" prema Time magazinu?', ['Time 100 (2013)','Forbes 30 Under 30','Rolling Stone Greatest Artists','Billboard Hot 100'], 0, 'medium'),
    // Social media & fan culture
    q('Kako se zovu Justinovi obožavatelji?', ['Beliebers','Bieber Fever','JB Army','Beehive'], 0, 'easy'),
    q('Na kojoj platformi je Justin Bieber najprije stekao slavu?', ['YouTube','Instagram','TikTok','Myspace'], 0, 'easy'),
    q('Koji je Justinov nickname koji su mu dali fanovi?', ['JB / Biebs','J-Dog','B-Man','Bieber'], 0, 'easy'),
    q('Koji je Justinov hashtag koji je pokrenuo viralni trend?', ['#Beliebers','#TeamBieber','#BieberOrBelieve','#JB'], 0, 'hard'),
    q('Koliko pratitelja ima Justin Bieber na Instagramu (otprilike, 2024.)?', ['Više od 290 milijuna','Oko 150 milijuna','Oko 200 milijuna','Oko 250 milijuna'], 0, 'medium'),
    q('Justin Bieber je bio drugi (iza Cristiana Ronalda) najpraćeniji na Twitteru. Točno ili netočno?', ['Točno (neko doba)','Netočno — bio je prvi','Netočno — bio je treći','Netočno — nije bio u top 5'], 0, 'hard'),
    // Music videos
    q('Koji je redatelj snimio glazbeni video za "Baby"?', ['Diane Martel','Hype Williams','Spike Jonze','Joseph Kahn'], 0, 'hard'),
    q('Gdje je snimljen glazbeni video za "Sorry" (2015.)?', ['Auckland, Novi Zeland','Los Angeles','New York','Miami'], 0, 'hard'),
    q('Koja je plesačica postala viralna zahvaljujući video "Sorry"?', ['Parris Goebel (ReQuest Dance Crew)','Ciara','Laurie Ann Gibson','Brian Friedman'], 0, 'hard'),
    q('Koji video Justina Biebera se proslavio parodijama i memovima zbog plesnih pokreta?', ['Baby','Boyfriend','Beauty and a Beat','One Less Lonely Girl'], 0, 'medium'),
    q('U kojemu je glazbenom videu Justin Bieber u tvornici čokolade (Willy Wonka vibe)?', ['Yummy','Peaches','Intentions','Lonely'], 0, 'medium'),
    // Trivia & fun facts
    q('Justin Bieber je u braku s Hailey od 2018. Ali kada su se vjenčali pred svjedocima? ', ['13. rujna 2018. (sudski)','30. rujna 2019. (crkvena ceremonija)','2018. i 2019.','Samo jednom 2019.'], 2, 'hard'),
    q('Koji je Justinov omiljeni jelo?', ['Pasta','Sushi','Burger','Pica'], 0, 'hard'),
    q('Justin Bieber ima tetovaže. Koliko ih otprilike ima (2023.)?', ['Više od 60','Oko 30','Oko 10','Oko 50'], 0, 'hard'),
    q('Koji je Justinov pas (poznata pasmine)?', ['Yorkies i bulldogs','Labrador','Golden retriever','Dalmatinac'], 0, 'hard'),
    q('U kojemu je gradu Justin Bieber imao legendarni "egg throwing" incident (jaja bacao na susjedovu kuću)?', ['Calabasas, Kalifornija','Malibu','Hollywood Hills','Beverly Hills'], 0, 'hard'),
    q('Koji je Justinov redatelj bio kritiziran i pozvan pred sud zbog tog incidenta?', ['Nitko — sam Justin se našao na sudu','Scooter Braun','Kenny Hamilton','Ryan Good'], 0, 'hard'),
    q('Koji Justinov dokumentarni film je emitiran na YouTubeu 2020. u 10 nastavaka?', ['Justin Bieber: Seasons','Justin Bieber: Never Say Never','Justin Bieber: Our World','Justin Bieber Journals'], 0, 'medium'),
    q('U kojemu je godištu Justin Bieber skinuo račun s Instagrama i vratio se?', ['2016','2015','2017','2018'], 0, 'medium'),
    q('Koji je Justin Bieber poznat kao "nasljednik" Michael Jacksona po nekim kritičarima?', ['Samo po pop statusu mlađahnih fanova','Po plesnim pokretima','Po vokalnom stilu','Po filantropiji'], 0, 'medium'),
    q('Kolika je Justinova visina?', ['175 cm','180 cm','170 cm','185 cm'], 0, 'medium'),
    q('Koji je Justinov automobil koji je uhvaćen dok vozi prebrzo?', ['Lamborghini Gallardo','Ferrari 458','Porsche 911','McLaren 650S'], 0, 'hard'),
    q('U kojemu je gradu Justin Bieber odrastao (ne rodio se)?', ['Stratford, Ontario','London, Ontario','Waterloo, Ontario','Kitchener, Ontario'], 0, 'medium'),
    q('Kako se zove Justinova mama glazbena?', ['Pattie Mallette','Linda Mallette','Sarah Bieber','Jane Mallette'], 0, 'medium'),
    q('Koji je Justinov polubrat?', ['Jazmyn i Jaxon Bieber','Jake Bieber','Josh Bieber','Nema polubrata'], 0, 'medium'),
    q('Koji je Justinov omiljeni NBA igrač bio (prijatelji)?', ['Chandler Parsons / LeBron James','Steph Curry','Kevin Durant','Kyrie Irving'], 0, 'hard'),
    q('Na kojemu je Justin Bieber glazbenom žanru odrastao slušajući?', ['R&B i hip-hop','Country','Rock','Jazz'], 0, 'easy'),
    // Songs deep dive
    q('Koji je refren pjesme "One Time"?', ['"Me plus you, imma tell you one time"','"Baby baby baby oh"','"Never say never"','"I\'m telling you one thing"'], 0, 'medium'),
    q('U kojemu albumu se nalazi "Mistletoe"?', ['Under the Mistletoe','My World 2.0','Believe','Journals'], 0, 'easy'),
    q('Koji je album sadrži "All I Want for Christmas Is You" (Mariah Carey cover na Justinovu izdanju)?', ['Under the Mistletoe','Journals','My World','Believe'], 0, 'medium'),
    q('Koja je Justinova pjesma o kajanju i ispričavanju (nije "Sorry")?', ['Nije kao "Sorry" — ali "2 Much" je o ljubavi','Confident','No Brainer','That Should Be Me'], 3, 'hard'),
    q('U kojoj su godini bili Biebsovi najveći hitovi objavljeni? (2015.)', ['Točno — Sorry, What Do You Mean, Love Yourself','Ne — 2014.','Ne — 2016.','Ne — 2013.'], 0, 'easy'),
    q('Koji je Justinov duet s Lukasom Grahamom?', ['Never Really Over','No specifičan hit','Hold On','Loved by You'], 0, 'hard'),
    q('Koja je Justinova božićna pjesma (2020.) nastala za humanitarne svrhe?', ['Holy (božić verzija)','Christmas Love','Rockin\' Around the Christmas Tree','Nema takve pjesme — ali "Lonely" je emotivna'], 0, 'hard'),
    q('Koje je trajanje hita "Baby" (original)?', ['Oko 3:30','Oko 4 minute','Oko 2:30','Oko 5 minuta'], 0, 'hard'),
    q('Koji je prvotni naslov hita "Sorry" bio u razvoju?', ['Uvijek je bio "Sorry"','Apologize','Forgive','Make It Up to You'], 0, 'hard'),
    q('Koji je Justinov album "Believe" dostigao pozicije na ljestvicama?', ['Broj 1 u SAD-u i Kanadi','Broj 2 u SAD-u','Broj 5 u SAD-u','Nije uspio ući u top 10'], 0, 'medium'),
    q('Na kojemu Justinovu albumu se nalazi hit "Company"?', ['Purpose','Changes','Justice','Believe'], 0, 'medium'),
    q('S kim je Justin snimio "10,000 Hours" — country duet?', ['Dan + Shay','Luke Combs','Morgan Wallen','Thomas Rhett'], 0, 'medium'),
    q('Koji Justinov singl je izašao na Dan zaljubljenih 2020.?', ['Anyone','Yummy','Lonely','Hold On'], 0, 'medium'),
    q('Koja je Justinova "lost" pjesma objavljena tek 2021. a snimana je 2009.?', ['Nema takvu — ali rariteti postoje','First Dance 2009','Bigger demo','Baby acoustic'], 0, 'hard'),
    q('Koji album Justin Bieber nije objavio između 2013. i 2015.?', ['Nije objavio studio album (samo Journals mixtape 2013)','Purpose','Changes','Believe 2'], 0, 'medium'),
    q('Koji je naslov Justinova spota koji je postigao 7 milijardi pregleda na YouTubeu?', ['Baby (s Ludarcisom)','Sorry','Love Yourself','What Do You Mean?'], 0, 'easy'),
    q('Koliko je singlova Justin Bieber objavio s albuma "Changes"?', ['Pet singla','Tri singla','Jedan singl','Sedam singla'], 0, 'hard'),
    q('Koji je Justinov "comeback" hit nakon kraće pauze u 2021.?', ['Peaches','Ghost','Anyone','Stay (s The Kid Laroi)'], 3, 'medium'),
    q('Tko je pisao većinu pjesama na albumu "Purpose" uz Justina?', ['Jason Boyd / "Poo Bear"','Max Martin','Ryan Tedder','Bruno Mars'], 0, 'hard'),
    q('Koji je Justinov reper koji je bio mentor krajem 2010-ih?', ['Chance the Rapper','Travis Scott','Drake','Lil Wayne'], 3, 'hard'),
    q('Koji je Justinov omiljeni YouTube kanal otkriven u intervjuima?', ['Nikad nije otkrio','Markiplier','PewDiePie','Casey Neistat'], 0, 'hard'),
    q('Koja je Justinova prva pjesma koja je premašila milijardu streamova na Spotifyju?', ['Love Yourself','Baby','Sorry','What Do You Mean?'], 0, 'medium'),
    q('Koji je Justinov singl s albuma "Justice" koji govori o tuzi za prošlom osobom?', ['Ghost','Peaches','Anyone','Holy'], 0, 'easy'),
    q('Koji je Justinov album osvajao certifikat dijamanta (Diamond) u SAD-u?', ['My World 2.0 (zbog "Baby")','Purpose','Changes','Believe'], 0, 'hard'),
    q('Koji bend je remixao Justinov "Baby" u hip-hop stilu rane 2010-ih?', ['Nema poznatih bendova — Ludacris je radio original rap dio','Lil Wayne','Drake','Nicki Minaj'], 0, 'hard'),
    q('Koja Justinova pjesma kaže: "I\'m in pieces, baby fix me"?', ['Nothing Like Us','Favourite Girl','Never Let You Go','Die in Your Arms'], 0, 'hard'),
    q('Koji je Justinov album zabranjen za prodaju u nekim zemljama zbog kontroverznih tekstova?', ['Nijedan album nije bio zabranjen','Believe','Purpose','Changes'], 0, 'hard'),
    q('Koji je Justinov hit koji svi smatraju "breakup anthem" namijenjen Seleni?', ['Love Yourself','Sorry','What Do You Mean?','Company'], 0, 'easy'),
    q('S kojim je izvođačem Justin nastupao na Super Bowlu?', ['Nikada nije nastupao na Super Bowlu halftime showu','Usher','Taylor Swift','Beyoncé'], 0, 'medium'),
    q('Koji je "Bieber Fever" fenomen?', ['Masovna obožavanjska histerija fanova iz ranih 2010-ih','Pjesma Justina Biebera','Televizijska emisija','Naziv turneja'], 0, 'easy'),
    q('U kojemu je godištu Justin Bieber proglasio "sabatical" pauzu od turneje?', ['2017','2016','2018','2019'], 0, 'medium'),
    q('Koji je razlog bio za otkazivanje Purpose World Tour 2017.?', ['Mentalno zdravlje i iscrpljenost','Ozljeda','COVID','Obiteljski razlozi'], 0, 'easy'),
    q('Koji je naziv albuma koji je Justin planirao ali nikad objavio?', ['Nije javno potvrđen neobjavljeni album','Phases','Better Days','Begin Again'], 0, 'hard'),
    q('Na kojoj je Justinov hit "Yummy" napisao uglavnom sam?', ['Da, uz "Poo Bear"','Ne, producirao je isključivo Max Martin','Ne, pisao je Ed Sheeran','Da, solo'], 0, 'hard'),
    q('Koji je TV show parodirao Justina Biebera u više navrata?', ['South Park i Saturday Night Live','The Simpsons','Family Guy','Bojack Horseman'], 0, 'medium'),
    q('Justin Bieber je u mladosti svirao koji instrumenti?', ['Bubnjevi, gitara, klavir i truba','Samo gitara','Samo klavir','Violina i klavir'], 0, 'medium'),
    q('Koji je Justin Bieber gostovao u seriji "CSI: Crime Scene Investigation"?', ['Da, u epizodi 2010.','Ne, to je bio Jonas Brothers','Da, u 2012.','Ne, nikada'], 0, 'medium'),
    q('Koji je Justinov singl bio "socijalni eksperiment" sniman tajno u Tampi, Floridi?', ['Beauty and a Beat (dio videa)','One Less Lonely Girl','Mistletoe','Confident'], 0, 'hard'),
    q('Koji je Justinov omiljeni filmski lik prema intervjuima?', ['Nije javno poznat','Spider-Man','Batman','Iron Man'], 0, 'hard'),
    q('Koji je Justinov tjelesni miris (parfem) nazvan?', ['Someday (2011.)','Believe','Purpose','One Time'], 0, 'medium'),
    q('Tko je snimio fotografiju za naslovnicu albuma "Purpose"?', ['Colin Dodgson','Annie Leibovitz','Rankin','Mert and Marcus'], 0, 'hard'),
    q('Koji je Justinov album koji je jedini live album?', ['Believe Acoustic / Under the Mistletoe su studio — nema live albuma','Live at the O2','Never Say Never: The Remixes','Believe Live'], 0, 'hard'),
    q('Koji je Justinov hit napravio rekordan skok na Spotifyju po broju streamova za jednu tjedan (2021)?', ['Peaches','Stay','Ghost','Holy'], 0, 'medium'),
    q('Koji je redatel dokumentarca "Justin Bieber: Our World" (2021. Amazon)?', ['Michael D. Ratner','Jon Chu','Davis Guggenheim','Shane Dawson'], 0, 'hard'),
    q('Koji je Justinov "merch drop" koji je rasprodan za manje od minute 2019.?', ['Drew House kolekcija','Purpose merch','Changes merch','Justice hoodie'], 0, 'medium'),
    q('Kako se zove Justinova fashion marka?', ['Drew House','Bieber Brand','JB Style','Changes Co.'], 0, 'easy'),
    q('Koji je Justinov kolega s kojim dijeli menadžera Scootera Brauna?', ['Ariana Grande i Taylor Swift (do 2019)','Ed Sheeran','Drake','Post Malone'], 0, 'medium'),
  ],

  // ─── ZARA LARSSON ──────────────────────────────────────────────────────────
  zara_larsson: [
    q('U kojoj je zemlji Zara Larsson rođena?', ['Šveđanska','Norveška','Danska','Finska'], 0, 'easy'),
    q('Kada je Zara Larsson rođena?', ['16. prosinca 1997.','16. prosinca 1996.','1. siječnja 1997.','22. studenog 1997.'], 0, 'medium'),
    q('Na kojemu je talent showu Zara pobijedila s 10 godina?', ['Talang (Švedska inačica BGT)','American Idol','X Factor','The Voice Sweden'], 0, 'medium'),
    q('Koji je Zarin debitantski EP iz 2013.?', ['Introducing','Uncover','1','Zaragon'], 0, 'medium'),
    q('Koji je Zarin debitantski studijski album iz 2014.?', ['1','Uncover','So Good','Poster Girl'], 0, 'easy'),
    q('Koji je Zarin međunarodni breakout singl iz 2015.?', ['Lush Life','Uncover','Never Forget You','Rooftop'], 0, 'easy'),
    q('Na kojem albumu se nalazi "Lush Life"?', ['So Good','1','Poster Girl','Venus'], 0, 'medium'),
    q('S kime je Zara Larsson snimila hit "Never Forget You" (2015.)?', ['MNEK','Alesso','Clean Bandit','Sigala'], 0, 'easy'),
    q('S kojim DJ-om je Zara snimila "Symphony" 2017.?', ['Clean Bandit','Kygo','Avicii','Zedd'], 0, 'easy'),
    q('Na kojemu albumu se nalazi "Symphony"?', ['So Good','Poster Girl','1','Venus'], 0, 'medium'),
    q('Koji je Zarin "empowerment" hit iz 2017.?', ['Ain\'t My Fault','Lush Life','Still In My Heart','WOW'], 0, 'medium'),
    q('Koji je treći Zarin studijski album?', ['Poster Girl (2021.)','So Good','1','Venus'], 0, 'medium'),
    q('Koji hit sa "Poster Girl" je postao viralan na TikToku 2021.?', ['Ruin My Life','Love Me Land','WOW','Talk About Love'], 0, 'medium'),
    q('S kime je Zara Larsson nastupala na Coachelli 2022.?', ['Nije nastupala','David Guetta','Kygo','Alesso'], 0, 'hard'),
    q('Koji je Zarin hit suradnja s Davidom Guettom iz 2018.?', ['This One\'s for You (FIFA 2016 song) / ili Crazy What Love Can Do','Flames','Better When You\'re Gone','Missing You'], 0, 'hard'),
    q('Na kojemu Zara Larsson albumu se nalazi "Don\'t Worry Bout Me"?', ['Poster Girl','So Good','1','Venus'], 0, 'medium'),
    q('Koji je Zarin omiljeni žanr glazbe koji izvodi?', ['Pop / R&B','Country','Electronic','K-pop'], 0, 'easy'),
    q('Koji je Zarin singl s Tysona Beckforda... ne — s MNEK? ', ['Never Forget You','Lush Life','Ain\'t My Fault','All The Time'], 0, 'easy'),
    q('Koji je Zarin famozni hit o zahtjevnoj emocionalnoj ljubavi 2018.?', ['Ruin My Life','One Mississippi','Still In My Heart','Talk About Love'], 0, 'easy'),
    q('Koji je Zarin album iz 2023.?', ['Venus','Poster Girl','So Good','1'], 0, 'medium'),
    q('Koja se pjesma s "Venus" (2023.) smatra Zarinim "banger" povratkom?', ['Can\'t Tame Her / Keep It Simple / WOW','Lush Life 2.0','Never Forget You 2023','Uncover remix'], 0, 'hard'),
    q('Koji je Zarinov hit za FIFA 2016 Svjetsko kupnp?', ['This One\'s for You (s Davidom Guettom)','Never Forget You','Lush Life','Symphony'], 0, 'medium'),
    q('Tko je Zarinov dečko/partner (prema medijima 2023.)?', ['Brian H. Scott Jr.','Liam Payne','Tyga','Marcus Rashford'], 0, 'hard'),
    q('Koji su Zarini roditelji po profesiji?', ['Otac glazbenik, majka socijalnica','Oba glumci','Oba glazbenici','Otac glumac, majka pjevačica'], 0, 'hard'),
    q('Zara Larsson je jako aktivna u kojemu pokretu?', ['Feminizmu i LGBTQ+ pravima','Borbi za klimu','Black Lives Matter','Anti-war pokretu'], 0, 'medium'),
    q('Koji je Zarinov poznati "condom challenge" video koji je objavio?', ['Stavljanje kondoma na ruku kao čarapa — viralni video 2016.','Nije radila takav video','Reklama za Durex','Humanitarni projekt'], 0, 'hard'),
    q('Na kojoj ljestvici je Zara Larsson bila na prvom mjesto singlom "Lush Life"?', ['UK Singles Chart','Billboard Hot 100','Hot Dance/Electronic Songs','ARIA Charts Australia'], 0, 'medium'),
    q('Koji je omiljeni Zarin emotivni hit o kraju veze koji nije "Ruin My Life"?', ['One Mississippi','Love Me Land','Don\'t Worry Bout Me','Still In My Heart'], 0, 'hard'),
    q('Koji je Zarin singl koji je izašao za Valentine\'s Day 2022.?', ['Look What You\'ve Done','Invisible','Poster Girl','Ain\'t My Fault'], 0, 'hard'),
    q('Koja je Zarina visina?', ['163 cm','170 cm','175 cm','158 cm'], 0, 'hard'),
    q('Koji je Zarina suradnja s Neicom (Neiked & Mae Muller)?', ['Better Days','Symphony 2','Lush Life remix','Never Let Me Down'], 0, 'medium'),
    q('Koji Zarin album sadrži pjesmu "All The Time"?', ['So Good','Poster Girl','Venus','1'], 0, 'medium'),
    q('Koji je Zarin glasovni opseg prema glazbenim kritičarima?', ['Mezzosopran','Sopran','Alt','Tenor'], 0, 'hard'),
    q('U kojemu su gradu Zara i njena sestra odrasle?', ['Stockholmu','Göteborgu','Malmöu','Uppsali'], 0, 'hard'),
    q('Koji je Zarin singl s DJ-om Alesso iz 2017.?', ['Nije bilo suradnje s Aless','Heroes (We Could Be)','Cool','Take My Breath'], 0, 'hard'),
    q('Koji je Zarinov hit koji je koristila kampaňa Hennessy?', ['Nema poznatog','Lush Life','Symphony','Never Forget You'], 0, 'hard'),
    q('Zara Larsson je gostovala u kojoj popularnoj seriji?', ['Nije gostovala u serijama','Emily in Paris','Euphoria','Sex Education'], 0, 'hard'),
    q('Koji je Zarin hip-hop izvođač koji je gostovao na jednom od njenih singlova?', ['Ty Dolla $ign','Drake','Cardi B','Nicki Minaj'], 0, 'medium'),
    q('Koji je Zarin singl koji se pojavio u zvučnom zapisu filma?', ['Nema poznatog ili "This One\'s for You" za FIFA','Never Forget You u TV seriji','Lush Life u reklami','Symphony u videogri'], 0, 'medium'),
    q('Koji je Zarin pop hit koji opisuje slobodu i nesputanost?', ['Love Me Land','Ain\'t My Fault','Lush Life','WOW'], 0, 'medium'),
  ],

  // ─── THE OFFICE ────────────────────────────────────────────────────────────
  the_office: [
    q('U kojemu se gradu odvija radnja serije "The Office"?', ['Scranton, Pennsylvania','Albany, New York','Stamford, Connecticut','Harrisburg, Pennsylvania'], 0, 'easy'),
    q('Kako se zove tvrtka u kojoj rade likovi?', ['Dunder Mifflin','Scranton Paper Company','Michael Scott Paper Company','Wernham Hogg'], 0, 'easy'),
    q('Tko je glumio Michaela Scotta?', ['Steve Carell','John Krasinski','Ed Helms','Rainn Wilson'], 0, 'easy'),
    q('Tko je glumio Dwighta Schrutea?', ['Rainn Wilson','John Krasinski','Ed Helms','B.J. Novak'], 0, 'easy'),
    q('Tko je glumio Jima Halperta?', ['John Krasinski','Steve Carell','Rainn Wilson','Craig Robinson'], 0, 'easy'),
    q('Tko je glumio Pam Beesly?', ['Jenna Fischer','Rashida Jones','Ellie Kemper','Mindy Kaling'], 0, 'easy'),
    q('Na kojoj je mreži emitirana "The Office" (US)?', ['NBC','ABC','CBS','Fox'], 0, 'easy'),
    q('Koliko je sezona imala američka verzija "The Officea"?', ['9','8','7','10'], 0, 'easy'),
    q('U kojoj je godini počela američka verzija serije?', ['2005','2004','2006','2003'], 0, 'easy'),
    q('Na kojoj je britanskoj seriji američka verzija bazirana?', ['The Office (BBC) redatelja Ricky Gervais','Parks and Recreation','Arrested Development','Extras'], 0, 'easy'),
    q('Tko je stvorio britansku verziju "The Office"?', ['Ricky Gervais i Stephen Merchant','Steve Carell','Greg Daniels','Mike Schur'], 0, 'medium'),
    q('Tko je kreator američke verzije "The Office"?', ['Greg Daniels','Steve Carell','Ricky Gervais','Michael Schur'], 0, 'medium'),
    q('Kako se zove Dwightova farma?', ['Schrute Farms','Dwight\'s Farm','Schrute Beet Farm','Lackawanna Farm'], 0, 'easy'),
    q('Koji je Dwightov omiljeni usjev?', ['Repa (beets)','Kukuruz','Krumpir','Soja'], 0, 'easy'),
    q('Koji je Jimov srednji ured pranke na Dwightu?', ['Stavljanje stvari u jello','Ukrašavanje kabine alu-folijom','Preseljenje stola','Prerušavanje u Dwighta'], 0, 'easy'),
    q('Kako se zove Michaelova dugogodišnja ljubav koja ga voli?', ['Holly Flax','Jan Levinson','Carol Stills','Donna'], 0, 'medium'),
    q('Tko je zamijenio Michaela Scotta kao šef na nekoliko epizoda?', ['Deangelo Vickers (Will Ferrell)','Andy Bernard','Dwight Schrute','Charles Miner'], 0, 'medium'),
    q('Koji je Andyev alma mater koji stalno spominje?', ['Cornell University','Harvard','Yale','Princeton'], 0, 'medium'),
    q('Kako se zove serija unutar serije u kojoj Dwight glumi?', ['Nije serija — Dwight je imao spin-off pilot','Sheriff of the Plains','The Dwight Schrute Show','Lackawanna County Sheriff'], 0, 'hard'),
    q('Koji je omiljeni film Michaela Scotta?', ['Threat Level Midnight (vlastiti)','Die Hard','Shrek','Godfather'], 0, 'medium'),
    q('Tko je Michaelova šefica i ljubavnica u tvrtki Dunder Mifflin?', ['Jan Levinson','Carol Stills','Holly Flax','Donna'], 0, 'medium'),
    q('U kojoj se epizodi Jim pita Pam na spoj za prvi put?', ['Casino Night (Season 2 finale)','Diversity Day','Health Care','The Dundies'], 0, 'medium'),
    q('Koji je lik poznat po frazi "That\'s what she said"?', ['Michael Scott','Dwight Schrute','Jim Halpert','Andy Bernard'], 0, 'easy'),
    q('Koji Michaelova fraza je postala meme: "I\'m not superstitious, but I am a little..."?', ['"stitious"','"careful"','"worried"','"nervous"'], 0, 'easy'),
    q('U kojoj sezoni napušta Michael Scott seriju?', ['Sezona 7','Sezona 8','Sezona 6','Sezona 9'], 0, 'medium'),
    q('Tko je zamijenio Michaela Scotta kao stalni šef u sezoni 8?', ['Andy Bernard','Robert California','Dwight Schrute','Deangelo Vickers'], 0, 'medium'),
    q('Koja je Kevina Malonea struka?', ['Računovođa','Prodavač','IT podrška','Recepcionar'], 0, 'easy'),
    q('Koji je Oscara zanimanje?', ['Računovođa','HR menadžer','Prodavač','Asistent'], 0, 'easy'),
    q('Tko je Toby Flenderson i zašto ga Michael mrzi?', ['HR menadžer kojeg Michael smatra negativnim','Prodajni direktor','Vlasnik tvrtke','Jeffreyjev zamjenik'], 0, 'easy'),
    q('Koji je Stanleyev omiljeni dan u tjednu?', ['Pretzel Day','Casual Friday','Bring Your Child to Work Day','St. Patrick\'s Day'], 0, 'medium'),
    q('U kojoj epizodi Michael hoda po žaru ("walking on coals")?', ['Beach Games','Grief Counseling','The Injury','Safety Training'], 0, 'medium'),
    q('Koji lik u seriji je glumac B.J. Novak?', ['Ryan Howard','Kelly Kapoor','Toby Flenderson','Andy Bernard'], 0, 'medium'),
    q('Koji lik glumi Mindy Kaling?', ['Kelly Kapoor','Phyllis Vance','Angela Martin','Meredith Palmer'], 0, 'easy'),
    q('Tko je Dwightova ljubavna interes tijekom cijele serije?', ['Angela Martin','Pam Beesly','Kelly Kapoor','Jan Levinson'], 0, 'easy'),
    q('Kako se zove Dwightova beet farma B&B?', ['Schrute Farms B&B','Schrute Lodge','Beet Barn','Dwight\'s Retreat'], 0, 'medium'),
    q('Tko su Jim i Pam nazvali svoju kći?', ['Cecelia Marie Halpert','Pam Jr.','Sarah Halpert','Jennifer Halpert'], 0, 'medium'),
    q('Koji je završni lik u seriji koji postane šef?', ['Dwight Schrute','Andy Bernard','Jim Halpert','David Wallace'], 0, 'medium'),
    q('U kojoj su se epizodi Jim i Pam vjenčali?', ['"Niagara" (Season 6)','Casino Night','Beach Games','Finale'], 0, 'medium'),
    q('Tko glumi Creed Bratten?', ['Creed Bratton (pravo ime)','Craig Robinson','Kevin Malone glumac','B.J. Novak'], 0, 'hard'),
    q('Koji je Creeds zanimanje u uredu?', ['Quality Assurance manager / nikad nije jasno','Prodavač','Računovođa','Asistent'], 0, 'medium'),
    q('Koji je najgledaniji singl iz serije "The Office" (tema)?', ['The Office Theme (Jay Ferguson)','Goodbye Michael','A.A.R.M.','Take a Bow'], 0, 'medium'),
    q('U kojoj epizodi Dwight glumi Michaela ("Night Out")?', ['Nije "Night Out" — glumi u više epizoda','Product Recall','The Fire','Fun Run'], 0, 'hard'),
    q('Koji je Phillisov muž?', ['Bob Vance (Vance Refrigeration)','Roy Anderson','Kevin Malone','Stanley Hudson'], 0, 'easy'),
    q('Tko pjeva na Dundies Award showu u seriji?', ['Michael Scott (kao domaćin)','Dwight','Jim','Kevin'], 0, 'easy'),
    q('Koji je Andyev alter ego u barbershop kvartetu?', ['Nard Dog','The Acapellator','Nard Man','Cornell Andy'], 0, 'easy'),
    q('Koja je glumica bila gost u seriji kao Michaelova sestra?', ['Nije imao sestru u seriji, ali jest... hm','Jennifer Aniston','Amy Adams','Carol od Michaela Carroll-a, Michael Scott Paper'], 0, 'hard'),
    q('Koji je Jimov drugi sin?', ['Philip Halpert','Michael Halpert','Dwight Halpert','James Jr.'], 0, 'hard'),
    q('Koji je najveći "cold open" prema fanovskim glasanjima?', ['Pretzel Day / Fire Drill','Dwight\'s Parking Spot','Kevin\'s Chilli','Jim as Dwight'], 2, 'medium'),
    q('Michael Scott rekao je: "I am Beyoncé, always." U kojoj situaciji?', ['Kad je rekao da je lider','Kad je objasnio svoju popularnost','Kad je usporedio sebe s pop zvijezdom','Na Dundies'], 1, 'hard'),
    q('Koji je lik rekao: "Whenever I\'m about to do something, I think, \'Would an idiot do that?\'"?', ['Dwight Schrute','Jim Halpert','Andy Bernard','Kevin Malone'], 0, 'easy'),
    q('U kojoj se epizodi Michael utrčava u fontanu?', ['Pilot / rane epizode','The Merger','Booze Cruise','Diwali'], 0, 'hard'),
  ],

  // ─── FRIENDS ───────────────────────────────────────────────────────────────
  friends: [
    q('Koliko je sezona imala serija "Friends"?', ['10','9','8','11'], 0, 'easy'),
    q('Na kojoj je mreži emitirana serija "Friends"?', ['NBC','CBS','ABC','Fox'], 0, 'easy'),
    q('Koje su godine počela serija "Friends"?', ['1994','1993','1995','1996'], 0, 'easy'),
    q('U kojemu je gradu smještena serija "Friends"?', ['New York City','Los Angeles','Chicago','Boston'], 0, 'easy'),
    q('Tko je glumio Rachel Green?', ['Jennifer Aniston','Courteney Cox','Lisa Kudrow','Reese Witherspoon'], 0, 'easy'),
    q('Tko je glumio Monica Geller?', ['Courteney Cox','Jennifer Aniston','Lisa Kudrow','Maggie Wheeler'], 0, 'easy'),
    q('Tko je glumio Chandler Bing?', ['Matthew Perry','Matt LeBlanc','David Schwimmer','Elliott Gould'], 0, 'easy'),
    q('Tko je glumio Joey Tribbiani?', ['Matt LeBlanc','Matthew Perry','David Schwimmer','James Michael Tyler'], 0, 'easy'),
    q('Tko je glumio Ross Geller?', ['David Schwimmer','Matt LeBlanc','Matthew Perry','Cole Sprouse'], 0, 'easy'),
    q('Tko je glumio Phoebe Buffay?', ['Lisa Kudrow','Jennifer Aniston','Courteney Cox','Jane Sibbett'], 0, 'easy'),
    q('Kako se zove bend u Centralnom parku gdje likovi sjede?', ['Central Perk','Coffee Express','Manhattan Brew','The Grind'], 0, 'easy'),
    q('Tko je bio konobar u Central Perku?', ['Gunther','Joey','Ross','Mike'], 0, 'easy'),
    q('Kako se zove Phoebeina popularna pjesma?', ['Smelly Cat','Fluffy Cat','Hungry Cat','Little Cat'], 0, 'easy'),
    q('U kojoj epizodi Ross i Rachel se počinju ljubiti po prvi put?', ['"The One Where Ross Finds Out"','The Pilot','The One with the Prom Video','The One after the Super Bowl'], 0, 'medium'),
    q('Koliko je puta Ross bio oženjen?', ['3','2','4','1'], 0, 'medium'),
    q('Kako se zove Rossov brat najbliži prijatelj kojeg Chandler stalno zezne?', ['Chandler i Ross jesu prijatelji — Chandler se ne zeza brata','Joey brat nije — Marcel majmun','Marcel (Rossov majmun)','Ben (Rossov sin)'], 2, 'hard'),
    q('Koji je Chandlerova fraza / karakteristično?', ['"Could this BE any more [adjective]?"','Could I BE wearing any more clothes?','Oh my God!','Pivot!'], 0, 'easy'),
    q('Kako se zove Moničin i Chandlerov stan?', ['Apartment 20 (oni naslijede Monici stan)','Apartment 19','Penthouse','Studio 10'], 0, 'hard'),
    q('Koji su stan Monica i Chandler naslijedili od drugarice?', ['Nisu naslijedili — to je bio Moničin stan od djetinjstva','Rachel je naslijedila','Phoebe ih je prepustila','Dali su ga Rossu'], 0, 'hard'),
    q('Tko je Rachel napustila na oltaru na početku serije?', ['Barry Farber','Ross Geller','Paul the Wine Guy','Tag Jones'], 0, 'medium'),
    q('Koji homonim uzrokuje čuveni Rossov krik "PIVOT!" dok seli sofu?', ['Pivot (okret skale)','Nije homonim, samo je krik','Lift','Push'], 0, 'easy'),
    q('U kojemu season finalu je Ross rekao "Rachel" umjesto Emily na vjenčanju?', ['Sezona 4','Sezona 3','Sezona 5','Sezona 6'], 0, 'medium'),
    q('Kako se zove Joeyev alter ego soap opere u seriji?', ['Drake Ramoray','Victor Kiriakis','Zach Morris','Nick Falco'], 0, 'medium'),
    q('U kojoj sapunici glumi Joey u seriji?', ['Days of Our Lives','General Hospital','All My Children','The Young and the Restless'], 0, 'easy'),
    q('Koji je Chandlerov postek koji nitko ne razumije?', ['Transponster (statistical analysis and data reconfiguration)','Accountant','Banker','IT'], 0, 'hard'),
    q('Tko je Moničin dječko iz visokolnog u koji se vrati?', ['Richard Burke (Tom Selleck)','Paul Stevens','Pete Becker','Fun Bobby'], 0, 'medium'),
    q('Koliko djece dobiju Monica i Chandler?', ['Dvoje (Erica i Jack — usvojeni)','Jedno','Troje','Nijednog'], 0, 'medium'),
    q('Koji je Rossov posao?', ['Paleontolog','Biolog','Kemičar','Geolog'], 0, 'medium'),
    q('Kako se zove Rossov sin iz braka s Carol?', ['Ben Geller','Jake Geller','Leo Geller','Danny Geller'], 0, 'medium'),
    q('Ko je Guntherov ljubavni interes cijele serije?', ['Rachel Green','Phoebe Buffay','Monica Geller','Elizabeth'], 0, 'easy'),
    q('Koji je Phoebin dvojnik u seriji?', ['Ursula (sestra blizanka)','Regina Phalange','Rache','Agnes'], 0, 'medium'),
    q('Koji je Phoebin lažni alter ego koji koristi za rezervacije?', ['Regina Phalange','Princess Consuela Bananahammock','Phoebe Buffay-Hannigan','Emily Litella'], 0, 'medium'),
    q('Kako se zove Phoebin muž na kraju serije?', ['Mike Hannigan (Paul Rudd)','David (geolog iz Rusije)','Eric','Frank Jr.'], 0, 'medium'),
    q('Koji je Joeyev omiljeni sendvič?', ['Meatball sub','Thanksgiving sandwich','Grilled cheese','Italian hoagie'], 0, 'medium'),
    q('Koji je Joey\'s catchphrase koji korisit kao udvarački?', ['"How you doin\'?"','Nice to meet you','What\'s up?','Wanna hook up?'], 0, 'easy'),
    q('Koje je godišnje dobno je najpoznatija Phoebeina Sanja moja?', ['Božić (Smelly Cat i glazba)','Proljeće','Jesen','Ljeto'], 0, 'hard'),
    q('Tko pjeva temu serije "I\'ll Be There for You"?', ['The Rembrandts','R.E.M.','Barenaked Ladies','Counting Crows'], 0, 'medium'),
    q('Koji glumac je preminuo 2023. — kolega iz "Friendsa"?', ['Matthew Perry (Chandler)','Matt LeBlanc','David Schwimmer','James Michael Tyler (Gunther)'], 0, 'easy'),
    q('Koji su posebne gostujuće uloge u "Friendsima"?', ['Brad Pitt, Reese Witherspoon, Julia Roberts i mnogi drugi','Samo Reese Witherspoon','Samo Brad Pitt','Samo Tom Selleck'], 0, 'medium'),
    q('Koji je Rossov dinosaur? Pravo ime?', ['Ross nema dinosaura — ima fosile (apato i brachiosaurus)','T-Rex kost','Marcel','Ben'], 0, 'hard'),
    q('Koji je popularni quote Rossova: "We were on a..."?', ['"break!"','"vacation"','"pause"','"hiatus"'], 0, 'easy'),
    q('U kojemu gradu Monica i Chandler kupuju kuću za kraj serije?', ['Westchester, New York','New Jersey','Connecticut','Long Island'], 0, 'medium'),
    q('Koji je glumac glumio Jackieja Goldschmidta (Moničin tata)?', ['Elliott Gould','Jerry Stiller','Larry David','James Earl Jones'], 0, 'medium'),
    q('Koji je Rachelinin otac zanimanje?', ['Liječnik','Odvjetnik','Bankir','Kirurg'], 0, 'medium'),
    q('Koji je rekorder po broju emitiranja (repriza) u SAD-u — ima li "Friends" taj rekord?', ['Da, jedna je od najrepriziranijih serija ikad','Ne, The Simpsons je ispred','Ne, Seinfeld je ispred','Ne, MASH je ispred'], 0, 'medium'),
    q('Koja je titula finalne epizode serije?', ['"The Last One"','"Goodbye"','"The End"','"Friends Forever"'], 0, 'medium'),
    q('U kojoj je godini završila serija "Friends"?', ['2004','2003','2005','2002'], 0, 'easy'),
    q('Koliko je Jennifer Aniston zaradila po epizodi u posljednjim sezonama?', ['1 milijun dolara','500,000$','2 milijuna$','750,000$'], 0, 'hard'),
    q('Što je smešno u Chandlerovim i Joeyem susjedstvima?', ['Ulike stan Numbers (19 i 20)','Žive na istom katu (7)','Stan 4 i 5','Suprotne strane hodnika'], 0, 'hard'),
    q('U kojoj je epizodi "The One with the Embryos" — što se događa?', ['Phoebe nosi embrije za brata, Monica i Chandler igraju kviz o znanju','Ross i Rachel se ljube','Joey gubi posao','Chandler i Monica se svađaju'], 0, 'hard'),
    q('Koji je Moničin i Rachelinin stan broj?', ['Stan 20 i 19 (mijenjaju se)','Stan 10','Stan 4B','Stan 1A'], 0, 'hard'),
  ],

  // ─── GAME OF THRONES ───────────────────────────────────────────────────────
  game_of_thrones: [
    q('Tko je autor knjiga na kojima je serija bazirana?', ['George R.R. Martin','J.R.R. Tolkien','Terry Goodkind','Robert Jordan'], 0, 'easy'),
    q('Kako se zove imaginarni kontinent u kojima se odvija radnja?', ['Westeros','Middleearth','Azeroth','Tamriel'], 0, 'easy'),
    q('Na kojoj je mreži emitirana serija "Game of Thrones"?', ['HBO','Netflix','Amazon Prime','Showtime'], 0, 'easy'),
    q('Koliko je sezona imala serija?', ['8','7','9','10'], 0, 'easy'),
    q('Koji je lik ubijen na "Crvenoj svadbi"?', ['Robb Stark i Catelyn Stark','Ned Stark','Joffrey Baratheon','Tywin Lannister'], 0, 'medium'),
    q('Tko je ubio Joffreyja Baratheoná?', ['Olenna Tyrell (i Littlefinger)','Tyrion Lannister','Sansa Stark','Daenerys'], 0, 'hard'),
    q('Kako se zove Nedov mač?', ['Ice','Needle','Longclaw','Oathkeeper'], 0, 'medium'),
    q('Kako se zove Aryin mač?', ['Needle','Ice','Oathkeeper','Dark Sister'], 0, 'easy'),
    q('Kako se zove Jonov mač?', ['Longclaw','Ice','Oathkeeper','Heartsbane'], 0, 'medium'),
    q('Koliko zmajeva ima Daenerys?', ['Tri (Drogon, Rhaegal, Viserion)','Dva','Jedan','Četiri'], 0, 'easy'),
    q('Kako se zove najveći Daenerysin zmaj?', ['Drogon','Rhaegal','Viserion','Balerion'], 0, 'easy'),
    q('Koje je Daenerysino puno ime i titule?', ['Daenerys Targaryen, Khaleesi of the Dothraki, Breaker of Chains, Mother of Dragons i više','Daenerys Stormborn samo','Khaleesi Targaryen','Daenerys Baratheon'], 0, 'medium'),
    q('Tko je Jon Snowov pravi otac?', ['Rhaegar Targaryen','Ned Stark','Robert Baratheon','Stannis Baratheon'], 0, 'medium'),
    q('Kako se zapravo zove Jon Snow (pravo ime)?', ['Aegon Targaryen','Jon Stark','Aemon Targaryen','Rhaegar Targaryen Jr.'], 0, 'medium'),
    q('Tko je ubio Ned Starka?', ['Ser Ilyn Payne (po naredbi Joffreyja)','Cersei Lannister','Tyrion Lannister','Jaime Lannister'], 0, 'medium'),
    q('Koja je Kuća Lannistera deviza?', ['"A Lannister always pays his debts" (nije službena, ali je popularna) / Hear Me Roar','Winter is Coming','Fire and Blood','Ours Is the Fury'], 0, 'hard'),
    q('Koja je službena deviza Kuće Stark?', ['"Winter is Coming"','We Do Not Sow','Ours Is the Fury','Hear Me Roar'], 0, 'easy'),
    q('Koja je deviza Kuće Targaryen?', ['"Fire and Blood"','Winter is Coming','Hear Me Roar','Growing Strong'], 0, 'easy'),
    q('Tko je sjedao na Željezno prijestolje na kraju serije?', ['Bran Stark','Jon Snow','Sansa Stark','Arya Stark'], 0, 'medium'),
    q('Koja je Aryin popis za smrt?', ['Popis osoba koje želi ubiti','Popis hrane','Popis knjiga','Popis mjesta'], 0, 'easy'),
    q('Tko je ubio Cersei Lannister na kraju?', ['Poginula je u ruševinama Crvene tvrđave (pod ciglama)','Jon Snow','Arya Stark','Daenerys'], 0, 'medium'),
    q('Koji je lik poznat po frazi "A girl has no name"?', ['Jaqen H\'ghar (i Arya Stark)','Daenerys','Cersei','Melisandre'], 0, 'medium'),
    q('Koji je Tyrionov nadimak?', ['Imp (Patuljak)','Kingslayer','Red Viper','The Spider'], 0, 'easy'),
    q('Koji je Jaimeov nadimak zbog ubojstva kralja?', ['Kingslayer','Imp','The Mountain','The Hound'], 0, 'easy'),
    q('Tko je ubio Oberyna Martella?', ['The Mountain (Gregor Clegane)','The Hound','Jaime Lannister','Cersei'], 0, 'medium'),
    q('Kako se zove sjever zid koji štiti od bijelih hodača?', ['"The Wall"','The Northern Wall','The Frozen Wall','The Ice Wall'], 0, 'easy'),
    q('Tko je komandant Noćne Straže (Night\'s Watch) koji je ubijen?', ['Lord Commander Mormont (ubijen od vlastite straže)','Jon Snow','Sam Tarly','Alliser Thorne'], 0, 'hard'),
    q('Tko je ubio Night Kinga (Kralja noći)?', ['Arya Stark','Jon Snow','Daenerys','Bran Stark'], 0, 'easy'),
    q('Koji je Brandov posebna moć?', ['Greensight i Warg (ulazak u životinje i viđenje prošlosti/budućnosti)','Vatra','Zmajevi','Magija leda'], 0, 'medium'),
    q('Koji je lik Hodor i što je posebno u njegovim zadnjim trenucima?', ['Drži vrata — "Hold the door" = Hodor','Ubijen od Night Kinga','Pobjegne iz Winterfella','Pošalje poruku'], 0, 'medium'),
    q('Tko je Varys?', ['Meštar šaptača (Master of Whispers), špijun','Meštar zakona','Lord zapovjednik straže','Savjetnik Cerseje'], 0, 'medium'),
    q('Koji je Littlefinger pravo ime?', ['Petyr Baelish','Peter Littlefinger','Petyr Lannister','Petr Baratheon'], 0, 'medium'),
    q('Koja je Melisandre religija i bog?', ['R\'hllor — Lord of Light','Vjera u Seven','Old Gods','Drowned God'], 0, 'medium'),
    q('Tko je Sandor Clegane drugi naziv?', ['The Hound','The Mountain','The Kingslayer','The Spider'], 0, 'easy'),
    q('Koji je grad poznat kao "King\'s Landing"?', ['Glavni grad Sedam Kraljevstva','Lannisportova luka','Grad na sjeveru','Vrijsna prijestolja'], 0, 'easy'),
    q('Koji je Khal Drogo?', ['Dothraki ratnik i Daenerysin muž','Targaryen vitez','Lannisters saveznik','Noćna Straža vođa'], 0, 'easy'),
    q('Koji su White Walkers?', ['Stari neprijatelji iz dalekog sjevera — vojska mrtvih','Lannisters vojnici','Dothraki konjici','Vojnici Noćne Straže'], 0, 'easy'),
    q('Koji je Cerseiin sin koji sjedne na prijestolje?', ['Joffrey Baratheon','Tommen Baratheon','Myrcella Baratheon','Stannis Baratheon'], 0, 'medium'),
    q('Kako se zove Daenerysina "homeland" (dom) koji želi vratiti?', ['Dragonstone i Iron Throne','Winterfell','Casterly Rock','Dorne'], 0, 'medium'),
    q('Tko je napisao scenarij "Crvene svadbe" (Red Wedding)?', ['George R.R. Martin (osobno napisao ovu epizodu)','David Benioff','Bryan Cogman','D.B. Weiss'], 0, 'hard'),
    q('Koliko je epizoda imala serija ukupno?', ['73','60','80','66'], 0, 'hard'),
    q('Koji je Samwell Tarly mentor?', ['Maester Aemon (Targaryen)','Maester Luwin','Qyburn','Grand Maester Pycelle'], 0, 'hard'),
    q('Koji je lik otkrio tajnu o Jonovom porijeklu?', ['Samwell Tarly (iz crkvenih knjiga) i Bran','Melisandre','Davos Seaworth','Varys'], 0, 'medium'),
    q('Koji je Tormund Giantsbane?', ['Wildling (slobodnjak) vođa, saveznik Jona Snowa','Lannister vojnik','Stark vazal','Noćna Straža zapovjednik'], 0, 'easy'),
    q('Koji je spin-off serija o "Game of Thrones" koji je izašao 2022.?', ['House of the Dragon','The Long Night','The Winds of Winter','Blood and Fire'], 0, 'easy'),
    q('Tko glumi Daenerys Targaryen?', ['Emilia Clarke','Sophie Turner','Maisie Williams','Natalie Dormer'], 0, 'easy'),
    q('Tko glumi Jona Snowa?', ['Kit Harington','Richard Madden','Nikolaj Coster-Waldau','Peter Dinklage'], 0, 'easy'),
    q('Tko glumi Tyriona Lannisters?', ['Peter Dinklage','Charles Dance','Nikolaj Coster-Waldau','Liam Cunningham'], 0, 'easy'),
    q('Koji je motto King\'s Landing?', ['Nema mottoa — to je grad, ne kuća','Power is power','What is dead may never die','Hear Me Roar'], 0, 'hard'),
    q('Koji je Cerseiin zlatni incest skandal?', ['Djeca su joj od brata Jaimea','Spavala je s Littlewingerom','Veza s Khal Drogom','Ljubavna afera s Tyrionom'], 0, 'easy'),
    q('Koji je Rhaegal (Daenerysov zmaj) ubio?', ['Ubijen je od Euronovih lađa (ballista)','Night King','Cersei','Jon Snow'], 0, 'medium'),
  ],

  // ─── HARRY POTTER ──────────────────────────────────────────────────────────
  harry_potter: [
    q('Tko je autor Harry Potter knjiga?', ['J.K. Rowling','J.R.R. Tolkien','Roald Dahl','C.S. Lewis'], 0, 'easy'),
    q('Kako se zove škola čaranja kojoj pohađa Harry Potter?', ['Hogwarts','Beauxbatons','Durmstrang','Ilvermorny'], 0, 'easy'),
    q('U kojoj je kući Harry Potter?', ['Gryffindor','Slytherin','Hufflepuff','Ravenclaw'], 0, 'easy'),
    q('Kako se zove Harryjev nadobni prijatelj?', ['Ron Weasley','Draco Malfoy','Neville Longbottom','Dean Thomas'], 0, 'easy'),
    q('Kako se zove Harryjeva pametna prijateljica?', ['Hermione Granger','Ginny Weasley','Luna Lovegood','Cho Chang'], 0, 'easy'),
    q('Kako se zove glavni negativac?', ['Lord Voldemort (Tom Riddle)','Draco Malfoy','Severus Snape','Bellatrix Lestrange'], 0, 'easy'),
    q('Koji je Harryjev omiljeni sport na metlama?', ['Quidditch','Broomstick Racing','Wizard Chess','Dragon Riding'], 0, 'easy'),
    q('Koja je Harryja čarobni palica od?', ['Hollyin drvo i feniksiovo pero','Hrast i zmajeva srčanica','Breza i kosmati crv','Jasen i jednorogovo dlaka'], 0, 'medium'),
    q('Kako se zove Harryjeva sova?', ['Hedwig','Errol','Crookshanks','Scabbers'], 0, 'easy'),
    q('Koji je Ronov ljubimac?', ['Scabbers (štakor — zapravo Peter Pettigrew)','Fang','Trevor','Crookshanks'], 0, 'medium'),
    q('Koji je Hermionein ljubimac?', ['Crookshanks (mačka)','Scabbers','Hedwig','Norberta'], 0, 'easy'),
    q('Kako se zove direktora Hogwartsa?', ['Albus Dumbledore','Severus Snape','Minerva McGonagall','Dolores Umbridge'], 0, 'easy'),
    q('Koji je nastavni predmet koji predaje Severus Snape u ranim knjigama?', ['Napitci (Potions)','Obrana od Mračnih vještina','Preobrazba','Aritromantija'], 0, 'medium'),
    q('Tko je pravi Princezin polukriv?', ['Severus Snape (Half-Blood Prince)','Draco Malfoy','Harry Potter','Tom Riddle'], 0, 'medium'),
    q('Koja je Hermionein čarolija za nevidljivost?', ['Nema "nevidljivosti" za nju — Harry ima plašt nevidljivosti','Disillusionment Charm','Bedazzlement Hex','Invisibility Spell'], 0, 'hard'),
    q('Koji je Harryjev plašt koji nasljeđuje?', ['Ogrtač nevidljivosti (Cloak of Invisibility)','Ogrtač Gryffindora','Ogrtač Dumbledorea','Ogrtač Merlinov'], 0, 'easy'),
    q('Tko je ubio Siriusa Blacka?', ['Bellatrix Lestrange','Voldemort','Lucius Malfoy','Dolores Umbridge'], 0, 'medium'),
    q('Tko je ubio Dumbledorea?', ['Severus Snape (na Dracoov zahtjev)','Voldemort','Bellatrix','Draco Malfoy'], 0, 'medium'),
    q('Koji je Harry na kraju uništio Voldemortove Horcruxe?', ['Da — svih sedam (plus sam Harry kao slučajni)','Samo tri','Ron ih je uništio','Hermione je uništila sve'], 0, 'medium'),
    q('Koliko je Horcruxova Voldemort napravio?', ['7 (plus slučajno Harry)','6','8','5'], 0, 'medium'),
    q('Koji je Harryjev otac?', ['James Potter','Sirius Black','Remus Lupin','Arthur Weasley'], 0, 'easy'),
    q('Koji je Harryjev majka?', ['Lily Potter (née Evans)','Molly Weasley','Narcissa Malfoy','Petunia Dursley'], 0, 'easy'),
    q('Kako se zove Harryjev ujak s kojim živi?', ['Vernon Dursley','Petunia Dursley','Dudley Dursley','Marge Dursley'], 0, 'medium'),
    q('U kojoj ulici stanuju Dursleyevi?', ['4 Privet Drive, Little Whinging, Surrey','12 Grimmauld Place','The Burrow','Godric\'s Hollow'], 0, 'easy'),
    q('Koji je čarobni napitak koji ga čini sretnim — Felix Felicis?', ['Liquid Luck — čini te sretnijim i uspješnijim','Polyjuice Potion','Amortentia','Veritaserum'], 0, 'medium'),
    q('Koji napitak mijenja izgled?', ['Polyjuice Potion','Felix Felicis','Amortentia','Veritaserum'], 0, 'easy'),
    q('Koji napitak prisiljava istinu?', ['Veritaserum','Polyjuice Potion','Amortentia','Draught of Living Death'], 0, 'medium'),
    q('Koji je omiljeni predmet Hermione?', ['Sve — a posebno Aritromantija i Rune','Napitci','Preobrazba','Obrana od mračnih vještina'], 0, 'medium'),
    q('Koji su Deathly Hallows (Darovi Smrti)?', ['Elder Wand, Cloak of Invisibility, Resurrection Stone','Sorting Hat, Sword, Cloak','Horcrux, Wand, Stone','Wand, Broom, Cloak'], 0, 'medium'),
    q('Tko je pjevao "Weasley Is Our King"?', ['Slytherin studenti (pjevali su ga protiv Rona)','Gryffindorstudenti za Rona','Hufflepuff','Ravenclaw'], 0, 'hard'),
    q('Koji je Seamus Figginsova čuvena osobina?', ['Niste mislili na Seanusa — Seamus Finnigan stalno eksplodira stvari','Leti najbrže','Zna sve čarolije','Nikad se ne smije'], 0, 'medium'),
    q('Koji je najteža čarolija (Unforgivable)?', ['Sve tri su jednako teške: Avada Kedavra, Cruciatus, Imperius','Avada Kedavra je najteža','Cruciatus je najteža','Imperius je najteža'], 0, 'hard'),
    q('Koji je Harryjev NEWT rezultat iz Obrane od mračnih vještina?', ['O (Outstanding) — nije eksplicitno navedeno u knjigama','A (Acceptable)','E (Exceeds Expectations)','T (Troll)'], 0, 'hard'),
    q('Kako se zove Voldemortovo pravo ime?', ['Tom Marvolo Riddle','Tom Voldemort','Marvolo Riddle','Thomas Riddle'], 0, 'medium'),
    q('Koji je Gryffindorov kućni duh?', ['Nearly Headless Nick','The Bloody Baron','The Fat Friar','Helena Ravenclaw'], 0, 'medium'),
    q('Koji je Slytherinov kućni duh?', ['Bloody Baron','Nearly Headless Nick','Fat Friar','Grey Lady'], 0, 'medium'),
    q('Koji je Neville Longbottom poseban po čemu?', ['I on je mogao biti "odabrani" — proročanstvo se moglo odnositi na njega','Ima najjače čarolije','Jedini Hufflepuff u grupi','Zna sva imena biljaka'], 0, 'medium'),
    q('Koji je Luna Lovegood kućna kuća?', ['Ravenclaw','Gryffindor','Hufflepuff','Slytherin'], 0, 'easy'),
    q('Tko je glumio Harryja Pottera u filmovima?', ['Daniel Radcliffe','Rupert Grint','Tom Felton','Eddie Redmayne'], 0, 'easy'),
    q('Tko je glumio Hermione Granger?', ['Emma Watson','Emma Roberts','Bonnie Wright','Helena Bonham Carter'], 0, 'easy'),
    q('Tko je glumio Rona Weasleyja?', ['Rupert Grint','Tom Felton','Matthew Lewis','Alfie Enoch'], 0, 'easy'),
    q('Tko je glumio Dumbledorea u prvim filmovima?', ['Richard Harris','Michael Gambon','Ian McKellen','Patrick Stewart'], 0, 'medium'),
    q('Tko je glumio Snapa?', ['Alan Rickman','Kenneth Branagh','Gary Oldman','Ralph Fiennes'], 0, 'easy'),
    q('Koji je Harryjev Patronus (zaštitni čarobnjak)?', ['Jelen (kao otac James)','Labud','Medvjed','Lav'], 0, 'medium'),
    q('Koji je Hermionein Patronus?', ['Vidra','Zec','Jelen','Mačka'], 0, 'medium'),
    q('Koji je Ronov Patronus?', ['Jack Russell terijer','Vjeverica','Zec','Lisica'], 0, 'medium'),
    q('Koji je Dumbledorev Patronus?', ['Feniks','Jelen','Lav','Orao'], 0, 'medium'),
    q('Koji je Snapin Patronus?', ['Košuta (Doe) — zbog ljubavi prema Lily','Zmija','Jelen','Mačka'], 0, 'hard'),
    q('Koliko je knjiga u Harry Potter seriji?', ['7','6','8','10'], 0, 'easy'),
    q('Koji je zadnja knjiga?', ['Harry Potter and the Deathly Hallows','Harry Potter and the Half-Blood Prince','Harry Potter and the Order of the Phoenix','Harry Potter and the Chamber of Secrets'], 0, 'easy'),
    q('Koji su Tri Čarobnjačka Turnira (Triwizard Tournament) zadaci u Plamenom peharu?', ['Zmaj, jezero, labirint','Zmaj, zmija, labirint','Zmaj, riba, zamak','Sfinga, jezero, labirint'], 0, 'medium'),
    q('Koji je lik Dobby?', ['Slobodni kućni vilenjak koji voli Harryja','Voldemortov sluga','Dumbledoreov vilenjak','Gryffindorov maskota'], 0, 'easy'),
    q('Tko je oslobodio Dobbyja?', ['Harry Potter (čarapu u knjizi Luciusa Malfoya)','Dumbledore','Hermione','Ron'], 0, 'medium'),
  ],
};

async function seed() {
  try {
    console.log('Inserting categories...');
    for (const cat of categories) {
      await pool.query(
        `INSERT INTO categories (id, name, emoji, description, color)
         VALUES ($1,$2,$3,$4,$5)
         ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, emoji=EXCLUDED.emoji, description=EXCLUDED.description, color=EXCLUDED.color`,
        [cat.id, cat.name, cat.emoji, cat.description, cat.color]
      );
      console.log(`  Category: ${cat.name}`);
    }

    console.log('\nSeeding questions...');
    let total = 0;
    for (const [categoryId, qs] of Object.entries(questions)) {
      for (const question of qs) {
        const shuffled = shuffleQuestionOptions(question.options, question.correct_index);
        const opts = shuffled.options.map((text, i) => ({ text, correct: i === shuffled.correctIndex }));
        await pool.query(
          `INSERT INTO questions (category_id, question, options, correct_index, difficulty)
           VALUES ($1,$2,$3,$4,$5)
           ON CONFLICT DO NOTHING`,
          [categoryId, question.question, JSON.stringify(opts), shuffled.correctIndex, question.difficulty]
        );
        total++;
      }
      console.log(`  ${categoryId}: ${qs.length} questions`);
    }

    // Update question counts
    await pool.query(`
      UPDATE categories c SET question_count = (
        SELECT COUNT(*) FROM questions q WHERE q.category_id = c.id AND q.active = true
      )
    `);

    console.log(`\nDone! ${total} questions seeded.`);
  } catch (err) {
    console.error('Seed error:', err);
    process.exit(1);
  } finally {
    await pool.end();
  }
}

seed();
