// Run: node server/seeds/questions.js
// Seeds ~360 questions across 6 categories

try { require('dotenv').config(); } catch {}
const { Pool } = require('pg');

const pool = new Pool({
  connectionString: process.env.DATABASE_URL || 'postgresql://localhost/quizzo',
  ssl: process.env.DATABASE_URL ? { rejectUnauthorized: false } : false,
});

// Helper — q(question, [A,B,C,D], correctIndex 0-based, difficulty)
function q(question, options, correct, difficulty = 'medium') {
  return { question, options, correct_index: correct, difficulty };
}

const questions = {

  geography: [
    q('Koji je glavni grad Hrvatske?', ['Zagreb','Split','Rijeka','Osijek'], 0, 'easy'),
    q('Na ušću kojih dviju rijeka leži Beograd?', ['Save i Dunava','Drine i Morave','Tise i Dunava','Save i Morave'], 0, 'medium'),
    q('Koji je najviši vrh Bosne i Hercegovine?', ['Maglić','Troglav','Vlašić','Prenj'], 0, 'medium'),
    q('Koja je najdulja rijeka u Hrvatskoj?', ['Sava','Drava','Kupa','Una'], 0, 'easy'),
    q('U kojoj se državi nalazi Nacionalni park Plitvička jezera?', ['Hrvatskoj','Bosni','Slovenija','Srbiji'], 0, 'easy'),
    q('Koji je drugi po veličini grad u Srbiji?', ['Novi Sad','Niš','Kragujevac','Subotica'], 0, 'easy'),
    q('Koje more zapljuskuje obalu Hrvatske?', ['Jadransko','Jonsko','Tirensko','Egejsko'], 0, 'easy'),
    q('Koji je glavni grad Sjeverne Makedonije?', ['Skoplje','Ohrid','Bitola','Tetovo'], 0, 'easy'),
    q('Koji je najviši vrh Balkana?', ['Musala','Korab','Triglav','Durmitor'], 0, 'hard'),
    q('Koliko otoka ima Hrvatska?', ['Više od 1000','Oko 300','Oko 500','Oko 750'], 0, 'medium'),
    q('Koja rijeka protječe kroz Zagreb?', ['Sava','Kupa','Drava','Una'], 0, 'easy'),
    q('Koji je najveći grad Crne Gore?', ['Podgorica','Nikšić','Herceg Novi','Kotor'], 0, 'easy'),
    q('U kojoj europskoj državi leži Mont Blanc?', ['Francuskoj','Italiji','Švicarskoj','Austriji'], 0, 'medium'),
    q('Koja je površinom najveća zemlja na svijetu?', ['Rusija','Kanada','Kina','SAD'], 0, 'easy'),
    q('Koji grad leži na rijeci Temi?', ['London','Pariz','Rim','Madrid'], 0, 'easy'),
    q('Koji je najduži rijeka u Europi?', ['Volga','Dunav','Rajna','Dnjepar'], 0, 'medium'),
    q('Koja je najnaseljenija zemlja u Europi?', ['Njemačka','Rusija','Francuska','Italija'], 1, 'medium'),
    q('Koji grad je poznat po Eiffelovom tornju?', ['Pariz','Rim','Berlin','Madrid'], 0, 'easy'),
    q('Koji je jedini grad koji se nalazi na dva kontinenta?', ['Istanbul','Kairo','Moskva','Beograd'], 0, 'medium'),
    q('Koja je najdublja jezero na svijetu?', ['Bajkal','Kaspijsko more','Tanjanika','Viktorija'], 0, 'medium'),
    q('Koji kontinent je površinom najveći?', ['Azija','Afrika','Sjeverna Amerika','Europa'], 0, 'easy'),
    q('Što je Amazonka?', ['Najdulja rijeka u Južnoj Americi','Najdulja rijeka na svijetu','Planina u Brazilu','More uz Brazil'], 0, 'easy'),
    q('Koji grad je poznat kao "Grad svjetla"?', ['Pariz','Venecija','Barcelona','Amsterdam'], 0, 'easy'),
    q('Koja planina dijeli Europu od Azije?', ['Ural','Alpe','Kavkaz','Karpati'], 0, 'medium'),
    q('Što je Sahara?', ['Najveća vruća pustinja na svijetu','Najveća pustinja na svijetu','Savana u Africi','Planinski lanac'], 0, 'medium'),
    q('Koji je glavni grad Australije?', ['Canberra','Sydney','Melbourne','Brisbane'], 0, 'medium'),
    q('U kojoj se zemlji nalazi Tadž Mahal?', ['Indiji','Pakistanu','Bangladešu','Nepalu'], 0, 'easy'),
    q('Koji je najmanji kontinent?', ['Australija','Europa','Antarktika','Sjeverna Amerika'], 0, 'easy'),
    q('Koja je najdulja kopnena granica na svijetu?', ['SAD-Kanada','Rusija-Kina','Kina-Mongolija','Argentina-Čile'], 0, 'hard'),
    q('Koji je najviši slap na svijetu?', ['Angel Falls','Niagara','Victoria','Iguazu'], 0, 'medium'),
    q('Koji je najveći ocean?', ['Tihi','Atlantski','Indijski','Arktički'], 0, 'easy'),
    q('Koji je glavni grad Japana?', ['Tokio','Osaka','Kioto','Hirošima'], 0, 'easy'),
    q('Koja rijeka prolazi kroz Egipat?', ['Nil','Eufrat','Tigris','Niger'], 0, 'easy'),
    q('Što je Kilimandžaro?', ['Najviši vrh Afrike','Najdulja rijeka Afrike','Jezero u Tanzaniji','Vulkanski archipelag'], 0, 'easy'),
    q('U kojoj se zemlji nalazi Venecija?', ['Italiji','Španjolskoj','Grčkoj','Portugalu'], 0, 'easy'),
    q('Koji je grad prijestolnica Brazila?', ['Brasília','São Paulo','Rio de Janeiro','Salvador'], 0, 'medium'),
    q('Koliko zemalja dijeli granicu s Rusijom?', ['14','10','12','16'], 0, 'hard'),
    q('Koja je zemlja poznata kao Zemlja izlazećeg sunca?', ['Japan','Kina','Koreja','Tajland'], 0, 'easy'),
    q('U kojoj je zemlji rijeka Ganges?', ['Indiji','Kini','Bangladešu','Nepalu'], 0, 'easy'),
    q('Koji je treći po visini vrh na svijetu?', ['Kangchenjunga','K2','Lhotse','Makalu'], 0, 'hard'),
    q('Koja je najdulja planinska kosa na svijetu?', ['Ande','Himalaja','Ural','Rocky Mountains'], 0, 'medium'),
    q('Što je Bosphorus?', ['Tjesnac između Europe i Azije','Rijeka u Rusiji','Planinski prijevoj','More uz Tursku'], 0, 'medium'),
    q('Koji je grad poznat kao "Vječni grad"?', ['Rim','Atena','Beograd','Kairo'], 0, 'easy'),
    q('Koja zemlja graniči s Bosnom i Hercegovinom na istoku?', ['Srbija','Hrvatska','Crna Gora','Kosovo'], 0, 'easy'),
    q('Koji je najpoznatiji fjord u Norveškoj?', ['Sognefjord','Hardangerfjord','Geirangerfjord','Lysefjord'], 0, 'hard'),
    q('Na kojim se otocima nalazi Panama City?', ['Nije na otocima, nalazi se na kopnu','Bahamima','Galapagosima','Karibima'], 0, 'medium'),
    q('Koji je glavni grad Kanade?', ['Ottawa','Toronto','Montreal','Vancouver'], 0, 'medium'),
    q('Koja je zemlja poznata kao domovina tulipana?', ['Nizozemska','Turska','Japan','Belgija'], 0, 'easy'),
    q('Koji je najveći jezero u Africi?', ['Viktorija','Tanganjika','Malavi','Albert'], 0, 'medium'),
    q('Koja je najdulja obalna linija na svijetu (po državi)?', ['Kanada','Norveška','Rusija','Australija'], 0, 'hard'),
    q('U kojoj se zemlji nalazi Akropola?', ['Grčkoj','Italiji','Turskoj','Egiptu'], 0, 'easy'),
    q('Koji je jedini kontinent bez volcana?', ['Australija','Europa','Sjeverna Amerika','Antarktika'], 0, 'hard'),
    q('Koja je metropola poznata kao "Grad vjetrova"?', ['Chicago','New York','Toronto','Houston'], 0, 'medium'),
    q('Koji je najduži kopneni prolaz između Europe i Azije?', ['Bosphorus','Sueski kanal','Panamski kanal','Gibraltar'], 0, 'medium'),
    q('Koji europski grad ima nadimak "Zlatni grad"?', ['Prag','Beč','Budimpešta','Varšava'], 0, 'medium'),
    q('Koja je najmanji zemlja na svijetu?', ['Vatikan','Monako','San Marino','Lihtenštajn'], 0, 'easy'),
    q('Koji je otok površinom najveći na svijetu?', ['Grenland','Borneo','Nova Gvineja','Madagaskar'], 0, 'medium'),
    q('U kojoj se zemlji nalazi Stonehenge?', ['Engleskoj','Irskoj','Škotskoj','Walesu'], 0, 'easy'),
    q('Koji je grad poznat po "Malo mermajdu"?', ['Kopenhagen','Amsterdam','Oslo','Stockholm'], 0, 'easy'),
    q('Koja africka zemlja je najnaseljenija?', ['Nigerija','Etiopija','Egipat','Kongo'], 0, 'medium'),
  ],

  history: [
    q('Koja je godina početka Prvog svjetskog rata?', ['1914','1912','1916','1918'], 0, 'easy'),
    q('Tko je bio prvi predsjednik SAD-a?', ['George Washington','Benjamin Franklin','Abraham Lincoln','Thomas Jefferson'], 0, 'easy'),
    q('Koji je rimski car izgradio Panteon?', ['Hadrijan','Augusts','Neron','Julije Cezar'], 0, 'hard'),
    q('Kada je pao Berlinski zid?', ['1989','1991','1987','1985'], 0, 'medium'),
    q('U kojoj je bitci Napoleon doživio konačni poraz?', ['Waterloo','Borodinu','Leipzig','Trafalgar'], 0, 'medium'),
    q('Tko je bio vođa nacističke Njemačke?', ['Adolf Hitler','Hermann Göring','Heinrich Himmler','Joseph Goebbels'], 0, 'easy'),
    q('Koja je civilizacija izgradila piramide u Gizi?', ['Egipćani','Sumerani','Feničani','Grci'], 0, 'easy'),
    q('Kada je Hrvatska proglasila neovisnost?', ['1991','1990','1992','1993'], 0, 'easy'),
    q('Koja je Magna Carta?', ['Listina o pravima Engleza iz 1215.','Rimski zakon iz 50. pr.Kr.','Napoleonov zakon','Ustav SAD-a'], 0, 'medium'),
    q('Tko je pronašao Ameriku 1492.?', ['Kristofor Kolumbo','Amerigo Vespuci','Vasco da Gama','Ferdinand Magellan'], 0, 'easy'),
    q('U kojoj je zemlji bila Kulturna revolucija 1960-ih?', ['Kini','Vijetnamu','Kubi','Sjevernoj Koreji'], 0, 'medium'),
    q('Koji je car bio poznat kao "Sunčev kralj"?', ['Luj XIV','Luj XVI','Napoleon','Karlo V'], 0, 'medium'),
    q('Kada je izbila Francuska revolucija?', ['1789','1776','1804','1815'], 0, 'easy'),
    q('Tko je napisao "O podrijetlu vrsta"?', ['Charles Darwin','Gregor Mendel','Louis Pasteur','Isaac Newton'], 0, 'easy'),
    q('Koji su se narodi sukobili u Peloponeskom ratu?', ['Atenjani i Spartanci','Grci i Perzijanci','Rimljani i Grci','Makedonci i Tračani'], 0, 'medium'),
    q('Koja je zemlja poslala prvi satelit u svemir?', ['SSSR','SAD','Kina','Francuska'], 0, 'easy'),
    q('Kada je SSSR raspao se?', ['1991','1989','1992','1990'], 0, 'easy'),
    q('Tko je bio posljednji car Rusije?', ['Nikola II','Aleksandar III','Aleksandar II','Ivan Grozni'], 0, 'easy'),
    q('Kako se zvala linija obrane između Francuske i Njemačke u 2. sv. ratu?', ['Maginotova linija','Ziegfriedova linija','Atlantski zid','Linija Hindenburg'], 0, 'hard'),
    q('Koji je bio povod Prvog svjetskog rata?', ['Atentat na Franza Ferdinanda','Invazija Belgije','Potapanje Lusitanije','Kriza u Sarajevu'], 0, 'medium'),
    q('U kojoj se bitci Napoleon pobijedio Austrijance i Ruse 1805.?', ['Austerlitz','Jena','Ulm','Wagram'], 0, 'hard'),
    q('Koja je zemlja bila poznata kao "Carstvo na kojemu sunce ne zalazi"?', ['Španjolska (u 16. st.)','Britanija','Rim','Mongolija'], 0, 'medium'),
    q('Koji je pokret vodio Mahatma Gandhi?', ['Nenasilan otpor (ahimsa) za neovisnost Indije','Oružanu pobunu protiv Britanaca','Komunistički pokret','Pan-azijski nacionalizam'], 0, 'easy'),
    q('Koja je zemlja bila prva koja je ženama dala pravo glasa?', ['Novi Zeland','Australija','Finska','Norveška'], 0, 'hard'),
    q('Tko je predvodio kubanski pokret revolucije?', ['Fidel Castro','Che Guevara','Raúl Castro','Camilo Cienfuegos'], 0, 'easy'),
    q('Kada je Jugoslavija službeno prestala postojati?', ['1992','1991','1995','1993'], 0, 'medium'),
    q('Što je bila Opijumski rat?', ['Sukob Kine i Britanije oko Opijuma u 19. st.','Rat SAD-a i Japana','Koloniziacija Indije','Bitka kod Šangaja'], 0, 'medium'),
    q('Tko je bio prvi čovjek na Mjesecu?', ['Neil Armstrong','Buzz Aldrin','Yuri Gagarin','John Glenn'], 0, 'easy'),
    q('Koji je car dao sagraditi Veliki kineski zid?', ['Qin Shi Huang','Han Wudi','Tang Taizong','Kublai Khan'], 0, 'medium'),
    q('Kada je Titanic potonuo?', ['1912','1914','1910','1916'], 0, 'easy'),
    q('Koji su narodi živjeli u Mezopotamiji?', ['Sumerani i Akađani','Egipćani i Feničani','Perzijanci i Medijci','Hetiti i Asirci'], 0, 'medium'),
    q('U kojoj je bitci Alexander Makedonski pobijedio Darija III?', ['Issos','Graniku','Gaugameli','Arbeli'], 0, 'hard'),
    q('Tko je bio vođa Azteka pri dolasku Španjolaca?', ['Moctezuma II','Cuauhtémoc','Itzcoatl','Ahuitzotl'], 0, 'medium'),
    q('Koja je bila prva nuklearna bomba bačena u ratu?', ['Hiroima, Japan','Nagasaki, Japan','Bikini Atoll','Nevada'], 0, 'easy'),
    q('Kada je Aleksandra Makedonskog umro?', ['323. pr.Kr.','356. pr.Kr.','301. pr.Kr.','336. pr.Kr.'], 0, 'medium'),
    q('Koji je ustanak izbio u Parizu 1871.?', ['Pariška komuna','Srpanjska revolucija','Revolucija 1848.','Nantska pobuna'], 0, 'hard'),
    q('Koji je car okrunio Karla Velikog 800. god.?', ['Papa Lav III','Papa Grgur III','Papa Ivan VIII','Papa Stjepan II'], 0, 'hard'),
    q('Koji je pokret u SAD-u borio za ukidanje ropstva?', ['Abolicionistički','Sufražetski','Progresivni','Populistički'], 0, 'easy'),
    q('Kada je Makedonija postala neovisna od Jugoslavije?', ['1991','1990','1992','1993'], 0, 'medium'),
    q('Kako se zvao pakt između nacista i Sovieta iz 1939.?', ['Molotov-Ribbentrop pakt','Pakt čelika','Trojni savez','Antikominternski pakt'], 0, 'medium'),
    q('Koji je vojskovođa pobijedio Rimljane kod Kanne?', ['Hanibal','Scipion','Pirro','Miltiades'], 0, 'hard'),
    q('Koja je zemlja bila domaćin prvog FIFA Svjetskog prventsva 1930.?', ['Urugvaj','Brazil','Argentina','Italija'], 0, 'medium'),
    q('Tko je bio vođa Kine kada je osnovan NR Kina 1949.?', ['Mao Zedong','Zhou Enlai','Deng Xiaoping','Chiang Kai-shek'], 0, 'easy'),
    q('Što je Bastilla?', ['Tvrđava u Parizu napadnuta 1789.','Dvorac Luja XIV','Most u Parizu','Zatvor u Marseilleu'], 0, 'medium'),
    q('Koji je vođa Mongolskog carstva u 13. st.?', ['Džingis-kan','Kublai-kan','Timur','Batu-kan'], 0, 'easy'),
    q('U kojoj je godini Drugi svjetski rat završio u Europi?', ['1945','1944','1946','1943'], 0, 'easy'),
    q('Tko je bio predsjednik SAD-a za vrijeme atentata 1963.?', ['John F. Kennedy','Lyndon B. Johnson','Dwight Eisenhower','Richard Nixon'], 0, 'easy'),
    q('Koji je naziv za hladnoratovsko vojnosavezničko natjecanje u svemiru?', ['Svemirska utrka','Naoružavanje','Berlinska kriza','Doktrina ograničenog rata'], 0, 'easy'),
    q('Gdje je potpisan mirovni sporazum koji je okončao 1. sv. rat?', ['Versailles','Trianon','Saint-Germain','Pariz'], 0, 'easy'),
    q('Koja se bitka smatra prekretnimcom na Istočnom frontu u 2. sv. ratu?', ['Staljingrad','Kursk','Moskva','Lenjingrad'], 0, 'medium'),
    q('Koji je Hrvatsku u 10. st. pokrstio?', ['Franački misionari u 9. st.','Bizant','Rim','Svetoslav'], 0, 'hard'),
    q('Koje je godine Bosna i Hercegovina proglasila neovisnost?', ['1992','1991','1993','1994'], 0, 'easy'),
    q('Tko je bio prvi čovjek koji je letio u svemiru?', ['Yuri Gagarin','Alan Shepard','John Glenn','Valentina Tereškova'], 0, 'easy'),
    q('Koji je slavni reformator crkve objavio 95 teza 1517.?', ['Martin Luther','Jan Hus','Ivan Calvin','Erazmo Roterdamski'], 0, 'medium'),
    q('Kada je Osmansko carstvo prestalo postojati?', ['1923','1918','1920','1922'], 0, 'medium'),
    q('Koji je grad bio glavnica Austro-Ugarske Monarhije?', ['Beč','Budimpešta','Prag','Zagreb'], 0, 'easy'),
    q('Koja je zemlja bila prva koja se digitalno potpuno prebacila na izborni sustav?', ['Estonija','SAD','Švicarska','Finska'], 0, 'hard'),
    q('Tko je osnivač islama?', ['Muhammed','Ibrahim','Isa','Musa'], 0, 'easy'),
    q('Koji su Europljani prvi doplovili u Ameriku?', ['Vikingzi (oko 1000. god.)','Kolumbo (1492.)','Amerigo Vespuci (1497.)','Magellan (1519.)'], 0, 'hard'),
    q('Kada se odigrao Domovinsk rat u Hrvatskoj?', ['1991-1995','1992-1995','1990-1994','1991-1996'], 0, 'easy'),
  ],

  sports: [
    q('Koji je klub najčešće osvajao Ligu prvaka u nogometu?', ['Real Madrid','Barcelona','Bayern München','AC Milan'], 0, 'easy'),
    q('Koji je grad bio domaćin Olimpijskih igara 2024.?', ['Pariz','Los Angeles','Tokio','Brisbane'], 0, 'easy'),
    q('Koji tenisač ima najviše Grand Slam naslova u povijesti (muški)?', ['Novak Đoković','Rafael Nadal','Roger Federer','Pete Sampras'], 0, 'medium'),
    q('Koja je zemlja pobijedila na FIFA Svjetskom pr. 2022.?', ['Argentina','Francuska','Brazil','Hrvatska'], 0, 'easy'),
    q('Koja je zemlja rekorder po broju osvajanja Svjetskog copa u nogometu?', ['Brazil','Njmačka','Italija','Argentina'], 0, 'easy'),
    q('Koji je košarkaš poznat kao "Koza"?', ['Michael Jordan','LeBron James','Kobe Bryant','Magic Johnson'], 0, 'easy'),
    q('U kojoj je godini Hrvatska ušla u FIFA finali Svjetskog pr.?', ['2018','2022','2014','2006'], 0, 'medium'),
    q('Koji klub je najbogatiji u svjetskom footballu (prema Forbes)?', ['Real Madrid','Manchester City','Barcelona','PSG'], 0, 'medium'),
    q('Koliko seta ima set za pobjedu u standardnom tenisu (muški Grand Slam)?', ['3','2','4','5'], 0, 'medium'),
    q('Koji je čuveni sprinter iz Jamajke koji je srušio rekord na 100m?', ['Usain Bolt','Asafa Powell','Yohan Blake','Justin Gatlin'], 0, 'easy'),
    q('U kojoj se disciplini natječe Luka Modrić?', ['Nogometu','Košarci','Tenisu','Rukometu'], 0, 'easy'),
    q('Koji je sport popularan u Srbiji i smatra se nacionalnim sportom?', ['Rukomet i košarka','Golf','Kriket','Baseball'], 0, 'easy'),
    q('Koji sport igra Đoković?', ['Tenis','Košarku','Rukomet','Stolni tenis'], 0, 'easy'),
    q('Koji je grad domaćin Maratona s najdužom tradicijom u SAD-u?', ['Boston','New York','Chicago','Los Angeles'], 0, 'medium'),
    q('Koliko igrača ima momčad u ragbiju uniiji?', ['15','13','11','7'], 0, 'medium'),
    q('Koji je sport poznat kao "Američki nogomet"?', ['Američki football','Kanadski football','Ragbi','Arena football'], 0, 'easy'),
    q('Koji je najbrži igrani sport na svijetu (brzina klizaljke)?', ['Hokej na ledu','Lacrosse','Polo','Badminton'], 0, 'hard'),
    q('Koje su boje olimpijskih prstenova?', ['Plava, žuta, crna, zelena, crvena','Plava, bijela, crvena, zelena, žuta','Sve boje duge plus bijela','Crvena, plava, bijela, crna, zelena'], 0, 'medium'),
    q('Koji je najduži teniski meč odigran na Wimbledonu?', ['Isner vs Mahut 2010.','Federer vs Nadal 2008.','Djokovic vs Nadal 2012.','Sampras vs Agassi 1995.'], 0, 'hard'),
    q('Koliko je poena potrebno za pobjedu u odbojci (set)?', ['25','21','15','30'], 0, 'easy'),
    q('Koji je najbrži rekord na 100m (sprint)?', ['9.58s (Usain Bolt)','9.63s','9.72s','9.69s'], 0, 'medium'),
    q('Koji klub je Luka Modrić napustio kako bi prešao u Real Madrid?', ['Tottenham','Dinamo Zagreb','Inter','Arsenal'], 0, 'medium'),
    q('Koji su sport "doma" Sjevernoameričke profesionalne lige MLB?', ['Baseball','Basketball','Football','Hockey'], 0, 'easy'),
    q('Koji je sport koji uključuje "grand slam" bez tenisa?', ['Golf','Rugbi','Baseball','Kriket'], 0, 'medium'),
    q('Koliko ekipa se natječe u NBA u redovnom dijelu sezone?', ['30','28','32','26'], 0, 'medium'),
    q('Koji je sport poznat po terminu "hat-trick"?', ['Svi sportovi s golovima/bodovima','Jedino hokej','Jedino kriket','Jedino snooker'], 0, 'medium'),
    q('Koja je zemlja domaćin turnira Roland Garros?', ['Francuska','Australija','Engleska','SAD'], 0, 'easy'),
    q('Koji je najgledaniji sportski događaj na svijetu?', ['FIFA Svjetsko pr. finali','Super Bowl','Tour de France','Wimbledon finale'], 0, 'medium'),
    q('Koji je sport kojim se Janica Kostelić bavila?', ['Alpskim skijanjem','Biciklizmom','Atletikom','Tenisem'], 0, 'easy'),
    q('U kojoj se godini Hrvatska rukometna reprezentacija pojvila na prvim Olimpijskim igrama?', ['1996','1992','2000','1988'], 0, 'hard'),
    q('Koji klub ima nadimak "Blazers"?', ['Portland Trail Blazers','Chicago Bulls','LA Lakers','Denver Nuggets'], 0, 'hard'),
    q('Koliko igrača ima momčad u vaterpolu?', ['7','9','6','11'], 0, 'medium'),
    q('Koji sport igra Djokovic?', ['Tenis','Košarku','Rukomet','Stolni tenis'], 0, 'easy'),
    q('Koji je jedini igrač koji je tri puta uzastopno pobijedio na Australian Openu (muški)?', ['Novak Đoković','Roger Federer','Rafael Nadal','Andy Murray'], 0, 'medium'),
    q('Koji je sport popularan u Škotskoj i smatra se porijeklom golfa?', ['Golf','Curling','Hurling','Šinty'], 0, 'hard'),
    q('Koji je rekord u skoku u dalj (muški)?', ['8.95m (Mike Powell)','9.12m','8.87m','9.03m'], 0, 'medium'),
    q('Koja zemlja nikad nije nastupila na olimpijskim igrama ali je pobijedila?', ['Sve zemlje koje su nastupile imaju medalje','Svaka od zemalja debitantica 2024.','Nijedna','Palestina'], 2, 'hard'),
    q('Koji je sport poznat po terminu "spike"?', ['Odbojci','Tenisu','Badmintonu','Stolnom tenisu'], 0, 'easy'),
    q('Koji je supermotorist Valentino Rossi?', ['Motociklistički prvak','Formula 1 vozač','Biciklistički prvak','Enduro prvak'], 0, 'easy'),
    q('Koji je sport FIBA organizacija?', ['Košarka','Football','Volleyball','Tenis'], 0, 'easy'),
    q('Koji je najveći stadion na svijetu?', ['Rungrado 1st of May (Sjeverna Koreja)','Camp Nou','Maracanã','Melbourne Cricket Ground'], 0, 'hard'),
    q('Koji je grad domaćin NBA tima "Celtics"?', ['Boston','Chicago','New York','Philadelphia'], 0, 'easy'),
    q('Koliko je Federer puta pobijedio na Wimbledonu?', ['8','6','7','9'], 0, 'medium'),
    q('Koji je sport koji se igra na terenu podijeljenem na "innings"?', ['Baseball','Cricket','Softball','Lacrosse'], 0, 'medium'),
    q('Koji je rekord u bacanju kugle (atletika, muški)?', ['23.56m','22.00m','24.11m','21.85m'], 0, 'hard'),
    q('Koji je grad domaćin Super Bowla 2025.?', ['New Orleans','Las Vegas','Miami','Los Angeles'], 0, 'hard'),
    q('Koji klub je Mario Mandžukić osvajao Ligu prvaka?', ['Bayern München','Juventus','Atletico Madrid','Chelsea'], 0, 'medium'),
    q('Što je "Dijamantna liga"?', ['Serija atletičarskih mitinga','Teniski turnir','Biciklistička trka','Plivački kup'], 0, 'medium'),
    q('Koji je vaterpolski napadaj je protupravno?', ['Faul u 5m zoni','Utopljavanje igrača','Bacanje lopte protivniku u glavu','Sve navedeno'], 3, 'hard'),
    q('Koji je jedini sportaš koji je osvajao i Zlatnu loptu i Zlatnu kopačku?', ['Lionel Messi','Cristiano Ronaldo','Ronaldo Nazário','Zinedine Zidane'], 0, 'hard'),
    q('Koji se sport igra lopatom i "kamenom" na ledu?', ['Curling','Hokej','Keling','Skejtanje'], 0, 'easy'),
    q('Koji je Nadal rekordar po broju pobjeda na Roland Garrosu?', ['14','11','13','12'], 0, 'medium'),
    q('Koji je sport FIFA, UEFA i CAF organizacija?', ['Nogomet','Rukomet','Košarka','Tenis'], 0, 'easy'),
    q('Koji je boksač poznat kao "The Greatest"?', ['Muhammad Ali','Joe Frazier','George Foreman','Mike Tyson'], 0, 'easy'),
    q('Koji je rekord u skoku u vis (muški)?', ['2.45m (Javier Sotomayor)','2.39m','2.42m','2.37m'], 0, 'hard'),
    q('Koji je klub Ivan Rakitić igrao u Europi?', ['Barcelona i Sevilla','Real Madrid i Valencia','PSG i Lyon','Juventus i Roma'], 0, 'medium'),
    q('Koji sport uključuje "slam dunk"?', ['Košarku','Odbojku','Američki football','Rugby'], 0, 'easy'),
    q('Koji je grad domaćin Wimbledona?', ['London','Manchester','Birmingham','Edinburgh'], 0, 'easy'),
    q('Koliko je Ronaldo (CR7) puta dobio Zlatnu loptu?', ['5','4','6','7'], 0, 'hard'),
    q('Koji je sport FIVB organizacija?', ['Odbojku','Košarku','Badminton','Squash'], 0, 'medium'),
    q('Koji je sport koji je nastao u Irskoj?', ['Gaelic football i hurling','Kriket','Ragbi','Polo'], 0, 'medium'),
  ],

  science: [
    q('Koji element ima atomski broj 1?', ['Vodik','Helij','Litij','Kisik'], 0, 'easy'),
    q('Što mjeri Richtero ljestvica?', ['Jačinu potresa','Brzinu vjetra','Visinu plime','Temperaturu laave'], 0, 'easy'),
    q('Koja je kemijska formula vode?', ['H₂O','HO₂','H₂O₂','OH'], 0, 'easy'),
    q('Koliko je kosten u ljudskom tijelu?', ['206','208','210','204'], 0, 'medium'),
    q('Koji je najteži prirodni element?', ['Uranij','Plutonij','Olovo','Zlato'], 0, 'medium'),
    q('Što je DNA?', ['Dezoksiribonukleinska kiselina — nosač genetskih informacija','Vrsta proteina','Dio stanične stijenke','Enzim u metabolizmu'], 0, 'easy'),
    q('Koji je plin najzastupljeniji u atmosferi Zemlje?', ['Dušik','Kisik','Argon','CO₂'], 0, 'easy'),
    q('Što je fotosinteza?', ['Proces kojim biljke pretvaraju sunčevu energiju u hranu','Disanje biljaka','Rast biljaka','Razmnožavanje biljaka'], 0, 'easy'),
    q('Koji je planetni sustav koji nije planeta u Sunčevom sustavu?', ['Pluton','Uran','Neptun','Satrun'], 0, 'easy'),
    q('Što je brzina zvuka u zraku (otprilike)?', ['343 m/s','300 m/s','500 m/s','250 m/s'], 0, 'medium'),
    q('Koji je organ koji pumpa krv kroz tijelo?', ['Srce','Pluća','Jetra','Mozak'], 0, 'easy'),
    q('Što je gravitacijska sila?', ['Sila privlačenja između masa','Sila odbijanja između naboja','Sila trenja','Elektromagnetska sila'], 0, 'easy'),
    q('Koji je kemijski element Au?', ['Zlato','Srebro','Bakar','Aluminij'], 0, 'easy'),
    q('Što je teorija evolucije?', ['Vrste se mijenjaju prirodnim odabirom','Vrste su nepromjenjive','Sve vrste su nastale od ribe','Evolucija je samo hipoteza'], 0, 'easy'),
    q('Koliko planeta ima Sunčev sustav?', ['8','9','7','10'], 0, 'easy'),
    q('Koji je najmanji planet Sunčevog sustava?', ['Merkur','Mars','Venus','Uran'], 0, 'medium'),
    q('Što je crna rupa?', ['Objekt s gravitacijom toliko jakom da ni svjetlost ne može pobjeći','Zvijezda bez svjetlosti','Praznina u svemiru','Dim galaksije'], 0, 'easy'),
    q('Koji je pH vrijednost čiste vode?', ['7','5','9','1'], 0, 'easy'),
    q('Što su neuroni?', ['Živčane stanice','Krvne stanice','Mišićne stanice','Koštane stanice'], 0, 'easy'),
    q('Koji je kemijski element Fe?', ['Željezo','Fluor','Fosfor','Francij'], 0, 'easy'),
    q('Što je antibiotik?', ['Lijek koji ubija bakterije','Lijek koji ubija viruse','Vitamin','Enzim'], 0, 'easy'),
    q('Koliko je kromosoma u normalnoj ljudskoj stanici?', ['46','44','48','42'], 0, 'medium'),
    q('Što je elektron?', ['Negativno nabijeni subatomski čestica','Pozitivno nabijeni čestica','Neutralna čestica u jezgri','Foton'], 0, 'easy'),
    q('Koji je najbrži konjski hodač (životinja, kopno)?', ['Gepard','Lav','Antilopa','Konj'], 0, 'easy'),
    q('Što je osmoza?', ['Difuzija otapala kroz polupropusnu membranu','Difuzija iona','Kemijska reakcija','Filtracija'], 0, 'medium'),
    q('Koji plin dišemo (esencijalni)?', ['Kisik','Dušik','Ugljikov dioksid','Argon'], 0, 'easy'),
    q('Što je frekvencija zvuka?', ['Broj titraja u sekundi, mjeri se u Hz','Visina zvuka u decibelima','Brzina zvuka','Amplituda vala'], 0, 'medium'),
    q('Koliko god traje Marsova godina?', ['Oko 687 Zemljinih dana','Oko 365 dana','Oko 400 dana','Oko 540 dana'], 0, 'medium'),
    q('Koji je najmanji element (masa)?', ['Vodik','Helij','Litij','Ugljik'], 0, 'easy'),
    q('Što je kloniranje?', ['Stvaranje genetski identičnih kopija organizma','Mutacija gena','Hibridizacija vrsta','Inbreeding'], 0, 'easy'),
    q('Što se zove ako zvijezda eksplodira?', ['Supernova','Pulsar','Kvasar','Bijela patuljica'], 0, 'easy'),
    q('Koji je organel koji sintetizira proteine?', ['Ribosom','Mitohondrij','Golgijev aparat','Endoplazmatski retikulum'], 0, 'medium'),
    q('Što je termodinamika?', ['Grana fizike koja proučava toplinu i energiju','Grana kemije','Grana biologije','Astronomija'], 0, 'easy'),
    q('Koji kemijski simbol je K?', ['Kalij','Krom','Kobalt','Kalcij'], 0, 'medium'),
    q('Što su Galápagosi poznati po?', ['Raznolika fauna koja je inspirirala Darwinovu teoriju','Vulkanizmu','Zlatnim rudnicima','Koralnim grebenima'], 0, 'medium'),
    q('Što je kvant energije fotona?', ['E = hf (energija = Planckova konstanta × frekvencija)','E = mc²','E = ½mv²','E = qV'], 0, 'hard'),
    q('Koji je plin uzrokuje staklenički efekt?', ['CO₂','N₂','O₂','Ar'], 0, 'easy'),
    q('Što je mitoza?', ['Dijeljenje stanice pri čemu nastaju dvije identične stanice','Seksualnem razmnožavanjem','Fuzija stanica','Apoptoza'], 0, 'medium'),
    q('Koji je kemijski element Hg?', ['Živa','Vodik','Helij','Hafnij'], 0, 'medium'),
    q('Što je relativnost?', ['Einsteinova teorija o prostoru, vremenu i gravitaciji','Princip neodređenosti','Zakon sile','Zakon energije'], 0, 'easy'),
    q('Koliko je dana u godini (ne prestupnoj)?', ['365','366','364','360'], 0, 'easy'),
    q('Koji je najdublji ocean?', ['Tihi','Atlantski','Indijski','Arktički'], 0, 'easy'),
    q('Što je kvark?', ['Subatomska čestica — gradivni blok protona i neutrona','Vrsta atoma','Vrsta molekule','Vrsta fotona'], 0, 'hard'),
    q('Koji su organi respiratornog sustava?', ['Pluća, bronhije, dušnik','Srce, jetra, bubrezi','Mozak, leđna moždina','Jednjak, trbuh, crijeva'], 0, 'easy'),
    q('Koji je element koji čini dijamant?', ['Ugljik','Silicij','Kisik','Dušik'], 0, 'easy'),
    q('Što je homeostaza?', ['Sposobnost organizma da održi unutarnju ravnotežu','Rast organizma','Adaptacija na okoliš','Genetska varijacija'], 0, 'medium'),
    q('Koji je najteži (gustoća) metalni element na sobnoj temperaturi?', ['Osmij','Iridij','Platina','Zlato'], 0, 'hard'),
    q('Što je elektromagnetski val?', ['Val koji se širi bez medija, uključuje svjetlost','Val koji zahtijeva medij','Zvučni val','Seizmički val'], 0, 'medium'),
    q('Koliko elektrona ima atom vodika?', ['1','2','0','3'], 0, 'easy'),
    q('Što je Nobel nagrada za kemiju 2023. dodjeljena za?', ['Kvantne točke','CRISPR','Proteinska struktura','Baterijska tehnologija'], 0, 'hard'),
    q('Koji je najduži nerv u tijelu?', ['Ishijatički nerv','Vagusni nerv','Optički nerv','Radijalni nerv'], 0, 'medium'),
    q('Koji je element u prvom redu periodnog sustava s velikim atomskim brojem?', ['Neon','Fluor','Argen','Klor'], 0, 'hard'),
    q('Što je placentalni sisavac?', ['Sisavac čiji se mladunci razvijaju u maternici','Sisavac koji liježe jaja','Sisavac koji nosi mlade u tobolcu','Vrsta reptila'], 0, 'easy'),
    q('Koji je organ koji filtrira krv i produvira urin?', ['Bubreg','Jetra','Slezena','Žučni mjehur'], 0, 'easy'),
    q('Što je fuzija?', ['Spajanje lakih atomskih jezgara uz oslobađanje energije','Dijeljenje teških jezgara','Kemijska veza','Radioaktivni raspad'], 0, 'medium'),
    q('Koji se plin koristi u LED žaruljama za fluorescentno osvjetljenje?', ['Argon','Kripton','Neon','Ksenon'], 0, 'hard'),
    q('Što je ekosustav?', ['Zajednica živih organizama i njihov fizički okoliš','Samo biljni život jednog područja','Samo životinjski život','Klimatski sustav'], 0, 'easy'),
    q('Koji je kemijski element srebra?', ['Ag','Si','Sr','Se'], 0, 'medium'),
    q('Što je plazmid?', ['Mali kružni DNA u bakterijama','Vrsta proteina','Organel stanice','Dio virusa'], 0, 'hard'),
    q('Koji je organ odgovoran za lučenje inzulina?', ['Gušterača','Jetra','Nadbubrežna žlijezda','Štitnjača'], 0, 'easy'),
    q('Što je termostat?', ['Uređaj koji regulira temperaturu','Mjerni instrument za tlak','Električni otpornik','Katalizator'], 0, 'easy'),
    q('Koji element je osnova organskog života?', ['Ugljik','Dušik','Kisik','Fosfor'], 0, 'easy'),
  ],

  film_music: [
    q('Koji je film zaradio najviše u kinoblagajnama svih vremena (nominalni)?', ['Avatar (2009/2022)','Avengers: Endgame','Titanic','Star Wars: The Force Awakens'], 0, 'medium'),
    q('Tko je komponirao simfoniju "Beethovenova 9."?', ['Ludwig van Beethoven','Wolfgang Amadeus Mozart','Franz Schubert','Joseph Haydn'], 0, 'easy'),
    q('U kojoj godini je izašao film "Titanic" (Cameron)?', ['1997','1995','1999','2001'], 0, 'easy'),
    q('Koji je bend poznat po albumu "The Dark Side of the Moon"?', ['Pink Floyd','The Beatles','Led Zeppelin','Rolling Stones'], 0, 'easy'),
    q('Tko je glumio Jamesa Bonda u prvom Bond filmu "Dr. No"?', ['Sean Connery','Roger Moore','George Lazenby','Timothy Dalton'], 0, 'easy'),
    q('Koji je film dobio najviše Oscara u jednoj ceremoniji?', ['Ben-Hur (1959) / Titanic (1997) / Lord of the Rings: Return', 'Avatar', 'La La Land', 'Gone with the Wind'], 0, 'hard'),
    q('Tko je pjevao "Bohemian Rhapsody"?', ['Freddie Mercury / Queen','David Bowie','Mick Jagger','Elton John'], 0, 'easy'),
    q('Koji je najpoznatiji film Stanleya Kubricka?', ['2001: A Space Odyssey','The Shining','Full Metal Jacket','A Clockwork Orange'], 0, 'medium'),
    q('Koja je glumica dobila Oscar za "Monster\'s Ball"?', ['Halle Berry','Charlize Theron','Hilary Swank','Jennifer Connelly'], 0, 'medium'),
    q('Koji je bend snimio album "Abbey Road"?', ['The Beatles','The Rolling Stones','The Who','The Kinks'], 0, 'easy'),
    q('Koji je film redatelja Alfredda Hitchcocka iz 1960.?', ['Psycho','Vertigo','Rear Window','The Birds'], 0, 'medium'),
    q('Tko je napisao operu "La Traviata"?', ['Giuseppe Verdi','Giacomo Puccini','Wolfgang Mozart','Richard Wagner'], 0, 'medium'),
    q('Koji je glumac igrao Tonija Starka (Iron Man)?', ['Robert Downey Jr.','Chris Evans','Chris Hemsworth','Mark Ruffalo'], 0, 'easy'),
    q('Koji je album Michaela Jacksona najprovidavaniji ikad?', ['Thriller','Bad','Off the Wall','Dangerous'], 0, 'easy'),
    q('Koji je film s Leonardom DiCapriom o sanjanju unutar sanjanja?', ['Inception','Shutter Island','Interstellar','The Aviator'], 0, 'easy'),
    q('Koji je bend izveo "Stairway to Heaven"?', ['Led Zeppelin','Deep Purple','Black Sabbath','AC/DC'], 0, 'easy'),
    q('Koji je film dobio Zlatnu palmu u Cannesu 2019.?', ['Parasite','Once Upon a Time in Hollywood','Pain and Glory','Bacurau'], 0, 'medium'),
    q('Tko je pisac "Gospodara prstenova"?', ['J.R.R. Tolkien','C.S. Lewis','George R.R. Martin','Terry Pratchett'], 0, 'easy'),
    q('Koji je pjevač poznat po pesmi "Billie Jean"?', ['Michael Jackson','Prince','David Bowie','Stevie Wonder'], 0, 'easy'),
    q('Koji je film u kojem Brad Pitt glumi "Tyler Durden"?', ['Fight Club','Se7en','Troy','Snatch'], 0, 'easy'),
    q('Tko je komponirao "Četiri godišnja doba"?', ['Antonio Vivaldi','Johann Sebastian Bach','Wolfgang Mozart','George Frideric Handel'], 0, 'easy'),
    q('Koji je glazbeni žanr nastao u jamaici 1960-ih?', ['Reggae','Ska','Dancehall','Rocksteady'], 0, 'medium'),
    q('Koji je film zaradio prvi Oscara za Beste Picture 1929.?', ['Wings','The Jazz Singer','Sunrise','7th Heaven'], 0, 'hard'),
    q('Tko je glumio Harmionu Granger u Harryju Potteru?', ['Emma Watson','Emma Stone','Keira Knightley','Hermione Norris'], 0, 'easy'),
    q('Koji je najcenjeniji film po Rotten Tomatoes (između klazika)?', ['Citizen Kane','Casablanca','Schindler\'s List','Lawrence of Arabia'], 0, 'hard'),
    q('Koji je pjevač poznat kao "The King"?', ['Elvis Presley','Michael Jackson','Frank Sinatra','Nat King Cole'], 0, 'easy'),
    q('Koji glazbeni instrument ima žice i trzalicu/gudalo?', ['Violina','Truba','Flauta','Bubnjevi'], 0, 'easy'),
    q('Koji je film Christophera Nolana o Batmanu iz 2008.?', ['The Dark Knight','Batman Begins','The Dark Knight Rises','Batman Forever'], 0, 'easy'),
    q('Tko je vodio bendom "The Doors"?', ['Jim Morrison','Janis Joplin','Jimi Hendrix','Eric Clapton'], 0, 'easy'),
    q('Koji je glumac u svim filmovima Wesa Andersona?', ['Bill Murray','Owen Wilson','Jason Schwartzman','Adrien Brody'], 0, 'hard'),
    q('Koja je pevačica izvela "Rolling in the Deep"?', ['Adele','Amy Winehouse','Beyoncé','Rihanna'], 0, 'easy'),
    q('Koji je film u produkciji Pixara iz 2003. o ribici?', ['Finding Nemo','The Incredibles','Monsters, Inc.','Toy Story 3'], 0, 'easy'),
    q('Tko je napisao simfoniju "Nedovršena"?', ['Franz Schubert','Beethoven','Brahms','Dvořák'], 0, 'medium'),
    q('Koji je bend snimio "Hotel California"?', ['Eagles','Fleetwood Mac','Steely Dan','The Doobie Brothers'], 0, 'easy'),
    q('Koji je film o Titaniku iz 1997.?', ['Titanic','The Poseidon Adventure','The Perfect Storm','Deep Blue Sea'], 0, 'easy'),
    q('Tko je komponirao "Mesiju" (oratorij)?', ['Georg Friedrich Händel','Johann Sebastian Bach','Claudio Monteverdi','Henry Purcell'], 0, 'medium'),
    q('Koji je glumac igrao Jokerom u "The Dark Knight"?', ['Heath Ledger','Joaquin Phoenix','Jack Nicholson','Mark Hamill'], 0, 'easy'),
    q('Koji je pjevač poznat po hit "Shape of You"?', ['Ed Sheeran','Sam Smith','Charlie Puth','Shawn Mendes'], 0, 'easy'),
    q('Koji je film dobio Oscar za nejbolje animirani film 2003.?', ['Finding Nemo','Spirited Away','The Incredibles','Shrek'], 0, 'medium'),
    q('Tko je napisao "Hamleta"?', ['William Shakespeare','Christopher Marlowe','Ben Jonson','John Webster'], 0, 'easy'),
    q('Koji je žanr glazbe poznat po "8 bar" blues progressiji?', ['Blues','Jazz','Country','Rock'], 0, 'medium'),
    q('Koji film je prvi koristio CGI efekte?', ['Tron (1982)','The Abyss','Jurassic Park','Terminator 2'], 0, 'hard'),
    q('Koji je pjevač izveo "Like a Prayer"?', ['Madonna','Cyndi Lauper','Whitney Houston','Tina Turner'], 0, 'easy'),
    q('Koji je film Sergio Leonea iz 1966.?', ['The Good, the Bad and the Ugly','Once Upon a Time in the West','A Fistful of Dollars','Duck, You Sucker!'], 0, 'medium'),
    q('Tko je komponirao balet "Labuđe jezero"?', ['Tchaikovsky','Prokofjev','Strauss','Debussy'], 0, 'easy'),
    q('Koji je glazbeni festival poznat po Glastonbury?', ['Rock i pop festival u Engleskoj','Jazz festival u SAD-u','Opera festival u Salzburgu','Klasični festival u Beču'], 0, 'easy'),
    q('Koji je film s Meryl Streep o modnom magazinu?', ['The Devil Wears Prada','Kramer vs. Kramer','Sophie\'s Choice','Silkwood'], 0, 'easy'),
    q('Koji je bend snimio "Smells Like Teen Spirit"?', ['Nirvana','Pearl Jam','Soundgarden','Alice in Chains'], 0, 'easy'),
    q('Koji je film Davida Lyncha iz 2001.?', ['Mulholland Drive','Blue Velvet','Lost Highway','Twin Peaks: Fire Walk with Me'], 0, 'medium'),
    q('Tko je napisao "Romeo i Julija"?', ['William Shakespeare','Ovid','Alessandro Scaligero','Matteo Bandello'], 0, 'easy'),
    q('Koji je glumac poznat po "Taxi Driver" i "Raging Bull"?', ['Robert De Niro','Al Pacino','Dustin Hoffman','Jack Nicholson'], 0, 'easy'),
    q('Koji je pjevač poznat kao "The Weeknd"?', ['Abel Tesfaye','Drake','The Weeknd je pseudonim za Abela Tesfayea','Travis Scott'], 2, 'medium'),
    q('Koji je film Spielberga iz 1993. o dinosaurima?', ['Jurassic Park','Indiana Jones','Schindler\'s List','Empire of the Sun'], 0, 'easy'),
    q('Tko je komponirao operettu "Šišmiš"?', ['Johann Strauss II','Franz Lehar','Carl Zeller','Karl Millöcker'], 0, 'medium'),
    q('Koji je bend izveo "Don\'t Stop Believin\'"?', ['Journey','Foreigner','Styx','Boston'], 0, 'medium'),
    q('Koji je film Coppole o talijanskoj mafijaškoj obitelji?', ['The Godfather','Apocalypse Now','The Conversation','Rumble Fish'], 0, 'easy'),
    q('Tko je napisao "1984"?', ['George Orwell','Aldous Huxley','Ray Bradbury','H.G. Wells'], 0, 'easy'),
    q('Koji je pjevač poznat po "Purple Rain"?', ['Prince','Michael Jackson','David Bowie','Stevie Wonder'], 0, 'easy'),
    q('Koji je film Kubricka iz 1980. u horor žanru?', ['The Shining','Full Metal Jacket','Barry Lyndon','Eyes Wide Shut'], 0, 'easy'),
    q('Tko je dirigent koji je preminuo 1989., poznat po Berlinskoj filharmoniji?', ['Herbert von Karajan','Leonard Bernstein','Georg Solti','Claudio Abbado'], 0, 'medium'),
    q('Koji je pjevač nastupio na Superbowl 57 (halftime show)?', ['Rihanna','Beyoncé','Katy Perry','Lady Gaga'], 0, 'hard'),
  ],

  pop_culture: [
    q('Koji je meme poznat po slici psa s uzdignutim obrvama?', ['Doge (šiba inu)','Grumpy Cat','Success Kid','Hide the Pain Harold'], 0, 'easy'),
    q('Koji je film Marvela koji je zaradio više od 2 milijarde dolara 2019.?', ['Avengers: Endgame','Avengers: Infinity War','Spider-Man: No Way Home','Black Panther'], 0, 'easy'),
    q('Koja je serija "Game of Thrones" temeljena na knjigama?', ['A Song of Ice and Fire','The Witcher','Wheel of Time','The Name of the Wind'], 0, 'easy'),
    q('Koji je društveni mreža poznat po "tweeting"?', ['Twitter / X','Facebook','Instagram','TikTok'], 0, 'easy'),
    q('Koji je YouTuber dugo imao najviše pretplatnika?', ['PewDiePie','MrBeast','T-Series','YouTube Rewind'], 0, 'medium'),
    q('Koji je film o djevojci koja postaje čarobnica u Hogwartsu?', ['Harry Potter i kamen mudraca','Čarobnjak iz Oza','Narnia','The Worst Witch'], 0, 'easy'),
    q('Koji je brend poznat po "Just Do It" sloganu?', ['Nike','Adidas','Puma','Reebok'], 0, 'easy'),
    q('Koji je glazbeni žanr K-pop?', ['Korejski pop glazbeni žanr','Japanski pop','Kineska glazba','Tajvanski pop'], 0, 'easy'),
    q('Koji je TV show poznat po "zapadu lik ostrva" i preživljavanju?', ['Lost','Survivor','The Island','Naked and Afraid'], 1, 'easy'),
    q('Koji je "challenge" postao viralan 2014. uz skupljanje novca za ALS?', ['Ice Bucket Challenge','Mannequin Challenge','Harlem Shake','Running Man Challenge'], 0, 'easy'),
    q('Koji je brend jabuke (tech)?', ['Apple','Samsung','Huawei','LG'], 0, 'easy'),
    q('Koji je lik poznat po "Valar Morghulis"?', ['Game of Thrones likovi','Harry Potter likovi','Lord of the Rings','Breaking Bad'], 0, 'easy'),
    q('Koji je film o Barbari u ružičastom 2023.?', ['Barbie','Legally Blonde','Clueless','Legally Blonde 3'], 0, 'easy'),
    q('Koji je hashtag pokrenuo #MeToo pokret?', ['Tarana Burke (2006) i Alyssa Milano (2017)','Hillary Clinton','Emma Watson','Oprah Winfrey'], 0, 'hard'),
    q('Koji je streamer poznat po igranju Fortnite i postavljanju rekorda u pretplatinicima?', ['Ninja','Shroud','Dr Disrespect','TimTheTatman'], 0, 'easy'),
    q('Koji je emoji najpopularniji po podacima (2021)?', ['😂 (Face with Tears of Joy)','❤️','🙏','😭'], 0, 'medium'),
    q('Koji je igrica popularna u kojoj se gradi i ruši?', ['Minecraft','Roblox','Terraria','Stardew Valley'], 0, 'easy'),
    q('Koji je superjunak poznat po "S" znaku na prsima?', ['Superman','Spider-Man','Shazam','Silver Surfer'], 0, 'easy'),
    q('Koji je "binge-watch" serija Netflix iz 2013. o politici?', ['House of Cards','Stranger Things','Orange Is the New Black','The Crown'], 0, 'medium'),
    q('Koji je YouTube kanal poznat po naučnim videima (1-3 minute)?', ['Kurzgesagt','VSAUCE','TED-Ed','SciShow'], 0, 'medium'),
    q('Koji je meme poznat po "distracted boyfriend"?', ['Distracted Boyfriend','Woman Yelling at a Cat','Drake Hotline Bling','Two Buttons'], 0, 'easy'),
    q('Koji je Taylor Swift album iz 2023.?', ['The Tortured Poets Department','Midnights','Reputation','Folklore'], 0, 'medium'),
    q('Koji je film o čovjeku koji provodi isti dan iznova i iznova?', ['Groundhog Day','About Time','Edge of Tomorrow','Palm Springs'], 0, 'easy'),
    q('Koji je stan koji koriste influenceri za sadržaj na TikToku u SAD-u?', ['Content house / kolektiv','Pr house','Brand studio','Loft'], 0, 'medium'),
    q('Koji je lik iz igrice "The Legend of Zelda"?', ['Link','Zelda','Ganon','Sve navedeno'], 3, 'easy'),
    q('Koji je pjevač/pjevačica poznat/a po "Born This Way"?', ['Lady Gaga','Katy Perry','Rihanna','Beyoncé'], 0, 'easy'),
    q('Koji je film Disneya o djevojci na ledu?', ['Frozen','Mulan','Moana','Tangled'], 0, 'easy'),
    q('Koji je TV show o kemičaru koji se pretvara u prodavača droge?', ['Breaking Bad','Narcos','Ozark','The Wire'], 0, 'easy'),
    q('Koji je super powered show iz Netflixa s Millie Bobby Brown?', ['Stranger Things','Dark','Outer Banks','The OA'], 0, 'easy'),
    q('Koji je brend automobilà koji je Elon Musk osnovao?', ['Tesla','SpaceX','Rivian','Lucid'], 0, 'easy'),
    q('Koji je meme poznat po fotografiji muškarca koji se nudi kao crveni gumb?', ['Two Buttons','This is Fine','Blinking White Guy','Change My Mind'], 0, 'easy'),
    q('Koji je superjunak poznat po "Wakanda Forever"?', ['Black Panther','Thor','Iron Man','Captain America'], 0, 'easy'),
    q('Koji je igrica br. 1 na Steam po broju igrača (2024.)?', ['Counter-Strike 2','Dota 2','PUBG','Baldur\'s Gate 3'], 0, 'medium'),
    q('Koji je youtuber napravio "Mukbang" trend?', ['Korjski YouTuberi','Japanski','Kineski','Tajlandski'], 0, 'hard'),
    q('Koji je viral fenomen "OK Boomer" vezan uz?', ['Generacijski sukob između Boomera i Gen Z','Politički pokret','Meme iz gaming zajednice','Serija na Netflix'], 0, 'easy'),
    q('Koji je film o AI robotu 2014. s Oscarem Isaacom?', ['Ex Machina','Her','A.I. Artificial Intelligence','Blade Runner 2049'], 0, 'medium'),
    q('Koji je pjevač/bend poznat po "Despacito"?', ['Luis Fonsi ft. Daddy Yankee','J Balvin','Bad Bunny','Maluma'], 0, 'easy'),
    q('Koji je lik iz igrice "Super Mario" koji nosi plavi šešir?', ['Nema lika s plavim šeširom — Luigi nosi zeleni','Waluigi','Wario','Toad'], 0, 'hard'),
    q('Koji je "challenge" uključivao jedenje tampon kapsula (Tide)?', ['Tide Pod Challenge','Cinnamon Challenge','Fire Challenge','Milk Crate Challenge'], 0, 'easy'),
    q('Koji je TV show o preživljavanju na nenaseljenom otoku?', ['Survivor','Lost','The Island','Naked and Afraid'], 0, 'easy'),
    q('Koji je brend poznat po zelenom "mermaid" logotipu?', ['Starbucks','Costa Coffee','Tim Hortons','Dunkin\''], 0, 'easy'),
    q('Koji je igrica poznat po "battle royale" modu s 100 igrača?', ['Fortnite i PUBG','Call of Duty','Apex Legends','Sve navedeno'], 3, 'easy'),
    q('Koji je social media platforma poznat po "disappearing" stories?', ['Snapchat','Instagram','Facebook','WhatsApp'], 0, 'easy'),
    q('Koji je TV show o obitelji koja rukovodi carством droge u Medellínu?', ['Narcos','Snowfall','Power','Ozark'], 0, 'easy'),
    q('Koji je viral ples iz 2020. zbog TikToka?', ['Renegade (by Jalaiah Harmon)','Macarena','Gangnam Style','Harlem Shake'], 0, 'medium'),
    q('Koji je film Christophera Nolana o vremenu koje ide unatrag?', ['Tenet','Memento','Interstellar','Dunkirk'], 0, 'easy'),
    q('Koji je pjevač poznat po albumu "DAMN."?', ['Kendrick Lamar','Drake','J. Cole','Tyler, the Creator'], 0, 'easy'),
    q('Koji je Netflix original anime koji je postao hit 2021.?', ['Squid Game (nije anime) — ali Demon Slayer', 'Squid Game', 'Money Heist', 'Dark'], 1, 'hard'),
    q('Koji je brend čokolade s ljubičastom ambalaažom?', ['Milka','Cadbury','Toblerone','Ritter Sport'], 0, 'easy'),
    q('Koji je "dance challenge" viral sa Beyoncéinim "Renaissance"?', ['Break My Soul','Cuff It','Alien Superstar','Crazy in Love'], 1, 'hard'),
    q('Koji je film o hobitu koji putuje u planinski grad patuljaka?', ['The Hobbit: An Unexpected Journey','Lord of the Rings','The Silmarillion','Willow'], 0, 'easy'),
    q('Koji je brend patika poznat po "Swoosh"?', ['Nike','Adidas','Under Armour','Vans'], 0, 'easy'),
    q('Koji je pjevač poznat po "Can\'t Stop the Feeling"?', ['Justin Timberlake','Bruno Mars','Pharrell Williams','Justin Bieber'], 0, 'easy'),
    q('Koji je meme poznat po "We do a little trolling"?', ['Elon Musk tweet meme','Bernie Sanders mittens','Distracted Boyfriend','Hide the Pain Harold'], 0, 'medium'),
    q('Koji je TV show o uredu sa Stevenom Carelom?', ['The Office (US)','Parks and Recreation','Arrested Development','30 Rock'], 0, 'easy'),
    q('Koji je app za dating koji koristi "swipe right/left" mehaniku?', ['Tinder','Bumble','Hinge','OkCupid'], 0, 'easy'),
    q('Koji je film iz 2019. o jokerskom liku DC svemira?', ['Joker','Batman v Superman','Suicide Squad','Birds of Prey'], 0, 'easy'),
    q('Koji je youtuber poznat po MrBeast burgeru?', ['MrBeast','PewDiePie','Markiplier','Jacksepticeye'], 0, 'easy'),
    q('Koji je lik poznat po "I am Iron Man"?', ['Tony Stark','Steve Rogers','Thor','Bruce Banner'], 0, 'easy'),
    q('Koji je pjevač nastupao na Coachella 2023. s hologramom Tupaca?', ['Dr. Dre / Snoop Dogg — to je bilo 2012.','Kanye West','Jay-Z','Frank Ocean'], 0, 'hard'),
    q('Koji je viral trend 2023. na TikToku vezan uz Barbie film?', ['Barbiecore estetika i ružičasta boja','Wet hair look','Clean girl aesthetic','BookTok'], 0, 'easy'),
    q('Koji je igrica popularna u kojoj igraš kao lovac na monstere?', ['Monster Hunter','Dark Souls','God of War','The Witcher'], 0, 'medium'),
  ],
};

async function seed() {
  try {
    // First ensure schema is run
    console.log('Seeding questions...');

    let total = 0;
    for (const [categoryId, qs] of Object.entries(questions)) {
      for (const q of qs) {
        const opts = q.options.map((text, i) => ({ text, correct: i === q.correct_index }));
        await pool.query(
          `INSERT INTO questions (category_id, question, options, correct_index, difficulty)
           VALUES ($1, $2, $3, $4, $5)
           ON CONFLICT DO NOTHING`,
          [categoryId, q.question, JSON.stringify(opts), q.correct_index, q.difficulty]
        );
        total++;
      }
      console.log(`  ${categoryId}: ${qs.length} questions`);
    }

    // Update question counts
    await pool.query(`
      UPDATE categories c SET question_count = (
        SELECT COUNT(*) FROM questions q WHERE q.category_id = c.id AND q.active = true
      )
    `);

    console.log(`\nTotal: ${total} questions seeded successfully!`);
  } catch (err) {
    console.error('Seed error:', err);
  } finally {
    await pool.end();
  }
}

seed();
